// src/services/intent/regex-safety.ts
//
// Intent patterns are generated by an LLM (IntentLearner / admin-edit flow), approved by a
// single human skimming a JSON blob in Telegram, then compiled once and run with `.exec()`
// against every future message from every user for the lifetime of the intent. A pattern with
// catastrophic backtracking (e.g. `(a+)+b`) is invisible to a quick read but hangs Bun's
// single-threaded event loop for the whole process the moment someone sends a message that
// almost-but-not-quite matches it — a total bot outage triggered by one adversarial phrase.
// This module gives the learner/edit/loader paths a cheap, dependency-free gate against that
// class of pattern before it ever reaches `IntentMatcher`.

// Real intent patterns are short (`^(?:найди|search)\s+(.+)$` is ~25 chars); 300 chars is
// generous headroom for verbose phrase alternations while still ruling out patterns long
// enough to hide multiple stacked constructs a human reviewer would skim past.
const MAX_PATTERN_LENGTH = 300;

/** Wall-clock budget for a canary probe, in ms. A linear-time pattern resolves in low
 *  single-digit ms against any of the probe strings below; catastrophic backtracking blows
 *  this by orders of magnitude even on a short string. Set well above normal jitter (a busy
 *  CI box can add a few ms of noise) and well below the ~450ms+ observed for real catastrophic
 *  patterns at PROBE_LENGTH, so there is margin on both sides. */
const PROBE_BUDGET_MS = 80;

/** Length of the repeated-character run in each probe string. Long enough that slower-growing
 *  vulnerable shapes (ambiguous alternation inside a repeated group, e.g. `(a|aa)+`, which the
 *  structural check below cannot see — neither branch has its own quantifier) still cross
 *  PROBE_BUDGET_MS; short enough that even the worst observed shapes resolve in about a second,
 *  since this check runs synchronously and must stay bounded itself. */
const PROBE_LENGTH = 36;

/** Strings crafted to trip near-miss catastrophic backtracking without needing to know the
 *  pattern's alphabet — a repeated character run followed by one that can never complete a
 *  match forces a safe engine to fail fast and a catastrophic one to explode. Three alphabets
 *  (letters, digits, whitespace) cover the character classes real intent patterns use. */
const PROBE_STRINGS = [`${'a'.repeat(PROBE_LENGTH)}!`, `${'1'.repeat(PROBE_LENGTH)}!`, `${' '.repeat(PROBE_LENGTH)}\t`];

/** Skip a bracket character class (`[...]`) starting at `source[i] === '['`, returning the
 *  index just past the matching unescaped `]`. Inside a class, `+`, `*`, `(`, `)` are literal
 *  characters, not metacharacters — this keeps the scanner below from misreading e.g. `[a-z+*]`
 *  as a nested quantifier. */
function skipCharacterClass(source: string, start: number): number {
  const n = source.length;
  let i = start + 1;
  while (i < n && source[i] !== ']') {
    if (source[i] === '\\') {
      i += 2;
    } else {
      i++;
    }
  }
  return i + 1;
}

/**
 * Detect the classic catastrophic-backtracking shape: a quantified group (`(...)+`, `(...)*`,
 * `(...){n,}` with no upper bound) that itself contains another unbounded quantifier. This is a
 * structural "star-height > 1" heuristic (the same idea the `safe-regex` package uses), not a
 * full backtracking simulator — it catches the constructs that show up in practice. Capturing,
 * non-capturing (`(?:...)`), named (`(?<name>...)`), and lookaround groups all start with `(`
 * and are treated uniformly; the group's own semantics don't change the depth/quantifier count.
 */
function hasNestedQuantifier(source: string): boolean {
  const n = source.length;
  let i = 0;
  while (i < n) {
    const ch = source[i];
    if (ch === '\\') {
      i += 2;
      continue;
    }
    if (ch === '[') {
      i = skipCharacterClass(source, i);
      continue;
    }
    if (ch === '(') {
      let depth = 1;
      let j = i + 1;
      let sawInnerQuantifier = false;
      while (j < n && depth > 0) {
        const c = source[j];
        if (c === '\\') {
          j += 2;
          continue;
        }
        if (c === '[') {
          j = skipCharacterClass(source, j);
          continue;
        }
        if (c === '(') {
          depth++;
        } else if (c === ')') {
          depth--;
        } else if (depth >= 1 && (c === '+' || c === '*')) {
          sawInnerQuantifier = true;
        } else if (depth >= 1 && c === '{') {
          const closeBrace = source.indexOf('}', j);
          if (closeBrace !== -1) {
            const body = source.slice(j + 1, closeBrace);
            // {n,} with no upper bound is unbounded repetition, same risk as + or *
            if (/^\d+,$/.test(body)) sawInnerQuantifier = true;
          }
        }
        j++;
      }
      const closeIdx = j - 1;
      const after = source[closeIdx + 1];
      const groupIsQuantified = after === '+' || after === '*' || after === '{';
      if (groupIsQuantified && sawInnerQuantifier) return true;
      i = closeIdx + 1;
      continue;
    }
    i++;
  }
  return false;
}

export interface PatternSafetyResult {
  safe: boolean;
  reason?: string;
}

/** Validate that a regex source is safe to compile and run against every future message. */
export function checkPatternSafety(source: string): PatternSafetyResult {
  if (source.length > MAX_PATTERN_LENGTH) {
    return { safe: false, reason: `pattern too long (${source.length} > ${MAX_PATTERN_LENGTH} chars)` };
  }

  let compiled: RegExp;
  try {
    compiled = new RegExp(source, 'i');
  } catch (err) {
    return { safe: false, reason: `pattern does not compile: ${err instanceof Error ? err.message : String(err)}` };
  }

  if (hasNestedQuantifier(source)) {
    return { safe: false, reason: 'pattern has a nested/unbounded quantifier (catastrophic backtracking risk)' };
  }

  for (const probe of PROBE_STRINGS) {
    const start = performance.now();
    compiled.exec(probe);
    const elapsed = performance.now() - start;
    if (elapsed > PROBE_BUDGET_MS) {
      return {
        safe: false,
        reason: `pattern took ${elapsed.toFixed(1)}ms against a ${probe.length}-char probe string (catastrophic backtracking risk)`,
      };
    }
  }

  return { safe: true };
}
