// src/services/voice/types.ts
import { logger } from '../../utils/logger';

export const voiceLogger = logger.child({ module: 'voice' });

/** The part of a WebSocket the streaming STT clients use; a real `WebSocket` satisfies it. */
export interface SttSocket {
  readonly readyState: number;
  send(data: string | Buffer): void;
  close(): void;
  onmessage: ((event: MessageEvent) => void) | null;
  onerror: ((event: Event) => void) | null;
  onclose: ((event: CloseEvent) => void) | null;
}

/** The languages a voice call can be held in. */
export type CallLanguage = 'ru' | 'en';

/** The call language for a stored language code; anything but English is held in Russian. */
export function toCallLanguage(language: string): CallLanguage {
  return language === 'en' ? 'en' : 'ru';
}

export interface CallReminderJobData {
  userId: number;
  eventId?: number;
  callLogId: number;
  ttsText: string;
  /** Raw language code as queued; normalize with `toCallLanguage` before use. */
  language: string;
  sessionId: string; // UUID generated by BullMQ enqueue
}
