// src/config/constants.ts

import { ruPlural } from '../services/event/formatters.ts';

// Rate limits
export const RATE_LIMIT = {
  MESSAGES_PER_MINUTE: 30,
  MESSAGES_PER_HOUR: 200,
  ADD_PER_HOUR: 20,
  EXPORT_PER_HOUR: 5,
  COOLDOWN_MS: 60_000,
  AI_PER_MINUTE: 10,
  AI_PER_HOUR: 60,
} as const;

// Defaults
export const DEFAULTS = {
  LANGUAGE: 'en' as const,
  TIMEZONE: 'UTC',
  REMINDER_MINUTES: 15,
  WEEK_STARTS_ON: 1 as const, // Monday
} as const;

// Callback data prefixes
export const CB = {
  EVENT_VIEW: 'ev',
  EVENT_EDIT: 'ee',
  EVENT_DELETE: 'ed',
  EVENT_DELETE_CONFIRM: 'edc',
  EVENT_RECURRENCE: 'er',
  EVENT_REMINDER: 'erm',
  ONBOARD_LANG: 'ol',
  ONBOARD_TZ: 'ot',
  ONBOARD_TZ_RETRY: 'otr',
  ONBOARD_COUNTRY: 'oc',
  ONBOARD_AGENDA: 'oa',
  MONTH_NAV: 'mn',
  SETTINGS: 'st',
  EDIT_FIELD: 'ef',
  ADD_STEP: 'as',
  RECURRENCE_DELETE: 'erd',
  ADD_RECURRENCE: 'ar',
  ADD_REC_END: 'are',
  ADD_SKIP: 'ask',
  HOLIDAYS: 'hl',
  NOTIFY: 'nf',
  GCAL: 'gc',
  IMG_DAILY: 'imd', // image daily: "imd:2026-03-11"
  IMG_WEEKLY: 'imw', // image weekly: "imw:2026-03-09"
  INVITATION_ACTION: 'inv',
  SHARE_CONFIRM: 'share_cf',
  SHARE_EVENT: 'share_evt',
  CALL_SETTINGS: 'csett',
  FEATURE_TOUR: 'ftour',
  INVITE_PICK: 'invp',
  INVITE_CONTACT: 'invc',
  EDIT_PROPOSAL: 'epr',
  INV_FORCE: 'inv_force',
  INV_RETIME: 'inv_retime',
  INV_CANCEL: 'inv_cancel',
  GROUP_SETTINGS_TZ: 'gst',
  TZ_CANCEL: 'tzc',
  TZ_TYPE_CITY: 'tzt',
  TZ_GEO_PICK: 'tzg',
  GEO_TZ_CONFIRM: 'gtzc',
  GEO_TZ_DISMISS: 'gtzd',
  SCENE_HELP: 'scene_help',
  ADD_CANCEL: 'add:cancel',
  LOCATION_GEO: 'loc_geo',
  LOCATION_CANDIDATE: 'loc_cand',
} as const;

// i18n messages
export const MSG = {
  en: {
    welcome: '🌍 Choose your language / Выберите язык:',
    tz_prompt: "Now let's set your timezone. The most accurate way is to share your location.",
    tz_detected: (tz: string, offset: string) => `Got it! Your timezone is ${tz} (${offset}).\nIs this correct?`,
    tz_confirm_yes: 'Yes ✓',
    tz_confirm_no: 'No, choose manually',
    geo_tz_confirm_prompt: (currentTz: string, newTz: string, offset: string) =>
      `📍 Your current timezone is <b>${currentTz}</b>.\nBased on your location, it looks like you're in <b>${newTz}</b> (${offset}).\n\nUpdating the timezone ensures reminders, agenda, and event times are shown correctly.\n\nUpdate timezone?`,
    geo_tz_confirm_btn: 'Yes, update ✓',
    geo_tz_dismiss_btn: 'No, keep current',
    geo_tz_updated: (tz: string, offset: string) => `✅ Timezone updated to ${tz} (${offset}).`,
    geo_tz_dismissed: 'OK, timezone left unchanged.',
    tz_same_from_location: (tz: string, offset: string) =>
      `📍 Your timezone is already ${tz} (${offset}) — no changes needed.`,
    share_location: '📍 Share Location',
    choose_manually: '⌨️ Choose Manually',
    country_prompt: 'Want to see public holidays in your calendar?',
    country_skip: 'Skip',
    agenda_prompt: "I can send you a morning summary of your day's events.\n\nChoose a time for the daily agenda:",
    onboard_done:
      "✅ All set! Here's what you can do:\n\n/add — create an event\n/today — today's schedule\n\nJust send me a text or voice message — I understand natural language and can create, edit, search events for you.",
    no_events_today: (date: string) =>
      `📅 ${date}\n\nNo events today. Want to plan something? Just describe it in a message, or use /add.`,
    no_events: 'No events in this range.',
    event_created: (title: string) => `✅ Created: "${title}"`,
    event_deleted: (title: string) => `🗑 Deleted: "${title}"`,
    event_updated: (title: string) => `✏️ Updated: "${title}"`,
    confirm_delete: (title: string) => `Delete "${title}"?`,
    search_no_results: 'No events found.',
    something_wrong: 'Something went wrong. Try again or use /help.',
    rate_limited: 'Slow down, too many messages.',
    add_title_prompt: "Let's create an event. What's the title?",
    add_time_prompt: 'When? (e.g., "tomorrow 18:00", "Mar 15 19:30")',
    add_duration_prompt: 'How long? (e.g., "1h", "30m", "2h30m") or skip for no end time.',
    add_description_prompt: 'Description? (send text or "skip")',
    add_location_prompt: 'Location? (send text or "skip")',
    edit_pick: 'Which event to edit? Pick from upcoming:',
    delete_pick: 'Which event to delete?',
    free_header: (date: string) => `📋 Free slots ${date}:`,
    pong: (ms: number) => `pong (${ms}ms)`,
    welcome_back: 'Welcome back! Send me a message or use /help.',
    recurrence_prompt: 'Repeat this event?',
    recurrence_end_prompt: 'When should it stop repeating?',
    recurrence_custom_prompt: 'Describe the recurrence (e.g., "every 2 weeks", "daily"):',
    recurrence_until_prompt: 'Send the end date (e.g., "Mar 30", "15 января"):',
    recurrence_count_prompt: 'How many times?',
    skip: 'Skip',
    holidays_menu: '🌍 <b>Holiday Subscriptions</b>',
    holidays_no_subs: 'No countries added yet. Tap "+ Add" to subscribe.',
    holidays_added: (country: string) => `✅ Subscribed to ${country}`,
    holidays_removed: (country: string) => `Removed ${country}`,
    holidays_set_primary: (country: string) => `${country} set as primary`,
    holidays_pick_region: 'Choose a region:',
    holidays_pick_country: 'Choose a country:',
    holidays_upcoming: '📅 <b>Upcoming Holidays</b>',
    holidays_none_upcoming: 'No upcoming holidays for your subscriptions.',
    holidays_day_off: '🎉 Day off!',
    holidays_manage_prompt: 'Choose a subscription to manage:',
    holidays_notify_on: (country: string) => `${country}: notifications ON`,
    holidays_notify_off: (country: string) => `${country}: notifications OFF`,
    ai_error: 'AI is temporarily unavailable. Use bot commands (/help).',
    ai_clear_history: 'Chat history cleared.',
    scene_help_btn: '🆘 Ask AI for help',
    notify_menu: '⚙️ Notification Settings',
    notify_morning: '🌅 Morning Agenda',
    notify_morning_status: (enabled: boolean, time: string) => `Morning agenda: ${enabled ? `✅ ${time}` : '❌'}`,
    notify_evening: '🌙 Evening Review',
    notify_evening_status: (enabled: boolean, time: string) => `Evening review: ${enabled ? `✅ ${time}` : '❌'}`,
    notify_reminders: '⏰ Default Reminders',
    notify_quiet: '🔇 Quiet Hours',
    notify_quiet_status: (enabled: boolean, start: string, end: string) =>
      `Quiet hours: ${enabled ? `✅ ${start} — ${end}` : '❌'}`,
    notify_pick_hour: 'Pick hour:',
    notify_pick_minute: 'Pick minute:',
    notify_updated: 'Settings updated',
    notify_intervals_label: (intervals: number[]) =>
      `Default reminders: ${intervals.map((m) => (m === 0 ? 'at start' : m >= 60 ? `${m / 60}hr` : `${m}min`)).join(', ')}`,
    gcal_onboarding:
      'Want to sync with Google Calendar?\n\nYour events will stay in the bot either way. Google Calendar sync is optional but gives you:\n- See bot events in your phone calendar\n- Changes in Google Calendar auto-sync to the bot\n- Two-way sync keeps everything up to date',
    gcal_onboarding_maybe_later: 'Maybe Later',
    gcal_not_configured: 'Google Calendar sync is not configured. Contact the admin.',
    gcal_already_connected: 'Google Calendar is already connected. Use /disconnect_google first to reconnect.',
    gcal_connect_prompt: '🔗 Connect Google Calendar to sync your events bidirectionally.',
    gcal_connect_button: 'Connect Google Calendar',
    gcal_connected: '✅ Google Calendar connected! Now pick which calendars to sync.',
    gcal_disconnected: '✅ Google Calendar disconnected. Your local events are untouched.',
    gcal_disconnect_confirm: 'Disconnect Google Calendar? Your events will stay in the bot.',
    gcal_disconnect_yes: 'Yes, disconnect',
    gcal_disconnect_no: 'Cancel',
    gcal_calendar_picker: 'Select calendars to sync (tap to toggle):',
    gcal_calendar_done: 'Done ✓',
    gcal_calendar_readonly: '(read-only)',
    gcal_calendars_saved: '✅ Calendar selection saved. Initial sync starting...',
    gcal_sync_complete: '✅ Initial sync complete. Your Google events are now in the bot.',
    gcal_revoked: '⚠️ Google Calendar connection lost. Use /connect_google to reconnect.',
    gcal_conflict: (title: string, winner: string) =>
      `⚠️ Sync conflict on "${title}"\n\n${winner === 'google' ? 'Google Calendar' : 'Local'} version was applied (more recent).`,
    gcal_status_connected: 'Connected ✅',
    gcal_status_not_connected: 'Google Calendar is not connected. Use /connect_google to start syncing.',
    gcal_status_sync_btn: '🔄 Sync now',
    gcal_status_calendars_btn: '⚙️ Calendars',
    gcal_status_sync_started: '⏳ Sync started',
    invite_error: 'Failed to send invitation.',
    invite_delivered: (title: string) => `📨 Invitation to "<b>${title}</b>" sent`,
    invite_deep_link: (title: string, url: string) =>
      `The user hasn't started the bot yet. Forward this link so they can accept:\n\n${url}\n\n(Invitation to "<b>${title}</b>")`,
    invitation_sent: 'Invitation sent',
    invitation_received: (title: string, from: string) =>
      `📨 <b>Invitation</b>\n${from} invites you to: <b>${title}</b>`,
    invitation_accepted: '✅ Invitation accepted',
    invitation_declined: '❌ Invitation declined',
    invitation_maybe: '🤔 Marked as maybe',
    invitation_cancelled: 'Invitation cancelled',
    invitation_expired: 'This invitation has expired',
    invitation_not_found: 'Invitation not found',
    invitation_already_sent: 'Invitation already sent to this user',
    invitations_disabled: 'This user has disabled invitations',
    invitation_response_accepted: (name: string, title: string) =>
      `📨 ${name} accepted your invitation to "<b>${title}</b>" ✅`,
    invitation_response_declined: (name: string, title: string) =>
      `📨 ${name} declined your invitation to "<b>${title}</b>" ❌`,
    invitation_response_maybe: (name: string, title: string) =>
      `📨 ${name} responded "maybe" to your invitation to "<b>${title}</b>" 🤔`,
    invite_propose_btn: 'Other time 🕐',
    invite_propose_ask: 'What time do you suggest?\nOr type: "tomorrow at 3pm"',
    invite_propose_plus30: '+30 min',
    invite_propose_plus60: '+1 hour',
    invite_propose_sent: (time: string) => `⏰ You suggested: ${time}`,
    invite_propose_notify: (name: string, event: string, time: string) =>
      `📅 ${name} suggests rescheduling <b>${event}</b> to ${time}`,
    invite_reschedule_btn: 'Reschedule 📅',
    invite_keep_btn: 'Keep original',
    invite_rescheduled_inviter: (time: string) => `✅ Event rescheduled to ${time}`,
    invite_rescheduled_invitee: (event: string, time: string) =>
      `✅ <b>${event}</b> rescheduled to ${time}. You are automatically accepted.`,
    invite_kept_inviter: '❌ Suggestion declined',
    invite_kept_invitee: (event: string, time: string) =>
      `❌ Your suggestion for <b>${event}</b> was declined. It stays at ${time}.`,
    invitations_from: (name: string) => `from ${name}`,
    invitations_to: (name: string) => `to ${name}`,
    privacy_current: (level: string) => `🔒 Current visibility: <b>${level}</b>`,
    share_preview: '📤 Preview — this is what will be shared:',
    share_sent: '✅ Shared successfully',
    share_cancelled: '❌ Share cancelled',
    no_events_to_share: 'No events to share for this period',
    call_settings_title: '📞 Voice Call Reminders',
    call_settings_enabled: 'Voice calls: ✅ Enabled',
    call_settings_disabled: 'Voice calls: ❌ Disabled',
    call_post_snooze: '⏰ Snoozed for 10 min',
    call_post_cancel: '❌ Event cancelled',
    call_post_ack: '✅ Got it',
    voice_response_enabled: '🎤 Voice responses enabled!',
    voice_response_disabled: '🎤 Ok, text only.',
    voice_demo_failed: '🎤 Voice enabled! Demo playback failed — voice replies will work from the next response.',
    cancelled: 'Cancelled.',
    voice_prompt: '🎤 Want voice replies?\nConvenient while driving, cooking, or on the go.',
    voice_prompt_yes: 'Yes, please',
    voice_prompt_no: 'No, text only',
    voice_stt_error: 'Could not recognize speech.',
    voice_error: 'Could not process voice message.',
    group_event_created: (groupRef: string, organizerLink: string) =>
      `📅 New event in ${groupRef}\n👤 Organizer: ${organizerLink}`,
    group_event_updated: (groupRef: string, organizerLink: string) =>
      `✏️ Event updated in ${groupRef}\n👤 Updated by: ${organizerLink}`,
    feature_tour_btn: '📖 All Features',
    feature_tour: [
      '<b>🤖 AI Assistant</b>\nJust text or voice-message me: "schedule a meeting tomorrow at 3pm", "what do I have next week?", "move my standup to 11:00". All bot features are available through chat — I understand context and execute commands.',
      '<b>📅 Calendar Management</b>\n/add — step-by-step event creation\n/today, /week, /month — different views\n/edit, /delete — modify events\n/free — find available time slots\nRecurring events with flexible rules.',
      '<b>🔔 Smart Reminders</b>\n/settings — morning agenda, evening review, quiet hours, voice calls, privacy\nMultiple reminders per event (15min, 1h, etc.)\nCustomizable notification intervals.',
      '<b>🌍 Holidays</b>\n/holidays — browse and subscribe to holidays from 100+ countries\nHolidays appear alongside your events in daily agenda.',
      '<b>📤 Sharing &amp; Invitations</b>\n/share today — share your agenda\n/invite @username — invite someone to an event\nEvent visibility: /settings → Privacy\nInline mode: type @HyperCalendarBot in any chat.',
      '<b>🖼 Visual Schedule</b>\nBeautiful calendar images are sent automatically with /today and /week commands.',
    ],
    settings: {
      title: '⚙️ Settings',
      back: '🔙 Back',
      close: '✖️ Close',
      categoryGeneral: '🌍 General',
      categoryNotifications: '🔔 Notifications',
      categoryCalls: '📞 Calls',
      categoryPrivacy: '🔒 Privacy',
      categoryVoice: '🎤 Voice',
      notificationsTitle: '🔔 Notifications',
      morningAgenda: 'Morning agenda',
      morningAgendaDesc: 'A brief daily agenda is sent every morning.',
      eveningReview: 'Evening review',
      eveningReviewDesc: "Tomorrow's events — convenient to check before bed.",
      quietHours: 'Quiet hours',
      quietHoursDesc: 'Reminders and calls are silenced during this time.',
      reminders: 'Reminders',
      remindersDesc: 'How long before an event the bot sends a reminder.',
      toggleMorning: 'Morning agenda',
      toggleEvening: 'Evening review',
      toggleQuiet: 'Quiet hours',
      editReminders: '⏰ Reminder intervals',
      reminderIntervalsTitle: '⏰ Reminder intervals',
      reminderIntervalsActive: (intervals: string) => `Active: ${intervals}`,
      reminderIntervalsNone: 'none',
      reminderIntervalsHint: 'Select how far ahead of an event to send a reminder.',
      reminderAtStart: 'at start',
      callsTitle: '📞 Voice calls',
      callsEnabled: 'Call reminders: ✅ Enabled',
      callsDisabled: 'Call reminders: ❌ Disabled',
      callsDesc1: 'The bot will call you before an event and read out the title.',
      callsDesc2: 'Works via a Telegram call — no phone number needed.',
      callsDesc3: 'Quiet hours also apply to calls.',
      toggleCallsEnable: '✅ Enable calls',
      toggleCallsDisable: '❌ Disable calls',
      privacyTitle: '🔒 Privacy',
      visibilityLabel: 'Event visibility',
      visibilityPrivate: 'Private',
      visibilityFreeBusy: 'Busy/free',
      visibilityFull: 'Full access',
      visibilityPrivateDesc: 'Only you see your events.',
      visibilityFreeBusyDesc: 'Others see you are busy but not what for.',
      visibilityFullDesc: 'Others see event titles and details.',
      inlineSearch: 'Inline search',
      inlineSearchDesc: 'Lets @HyperCalendarBot find you via inline mode.',
      invitations: 'Invitations',
      invitationsDesc: 'Allow other users to invite you to events.',
      cycleVisibility: (label: string) => `👁 Visibility: ${label} →`,
      voiceTitle: '🎤 Voice responses',
      voiceStatus: 'Voice responses',
      voiceNotSet: '❓ Not set',
      voiceEnabled: '✅ Enabled',
      voiceDisabled: '❌ Disabled',
      voiceDesc1: 'When on — the bot replies to messages with voice (TTS).',
      voiceDesc2: 'Works in Russian and English depending on the bot language.',
      voiceDesc3: 'Text reply is always sent; voice is additional.',
      toggleVoiceEnable: '✅ Enable voice responses',
      toggleVoiceDisable: '❌ Disable voice responses',
      showCountries: '🏳️ Choose a country:',
    },
    aiTools: {
      history: {
        notFound: 'No history found.',
      },
      actionLog: {
        notFound: 'No action log entries found.',
      },
      meta: {
        noHolidays: 'No upcoming holidays. You may not have country subscriptions set up.',
        unknownName: 'unknown',
        holidaysList: (lines: string) => `Upcoming holidays:\n${lines}`,
        foundUser: (id: number, name: string) => `Found user: telegram_id=${id}, name=${name}`,
        foundUserMtproto: (id: number, name: string) =>
          `Found user via MTProto: telegram_id=${id}, name=${name} (not a bot user yet — can only be reached via MTProto)`,
        addressBookEmpty: 'Address book is empty.',
        contactsList: (lines: string) => `Contacts:\n${lines}`,
        contactSaved: (name: string) => `Contact saved: ${name}`,
        contactFound: (data: string) => `Contact found: ${data}`,
        contactUpdated: (label: string) => `Contact updated: ${label}`,
        questionSent: 'Question sent. Waiting for user response.',
        dayImageRendering: (date: string) => `Image for ${date} is being rendered and will be sent as a photo.`,
        weekImageRendering: (weekStart: string) =>
          `Weekly calendar starting ${weekStart} is being rendered and will be sent as a photo.`,
        monthImageRendering: (month: string) =>
          `Monthly calendar for ${month} is being rendered and will be sent as a photo.`,
        callQueued: 'Call queued. You will receive a voice call shortly.',
        callFailed: (text: string) => `📞 Couldn't reach you by call.\n\n${text}`,
        gcalNotConnected: 'Google Calendar is not connected. You can connect it with /connect_google command.',
        gcalConnectedNoData: 'Google Calendar is connected, but calendar data is not available.',
        gcalConnectedHeader: 'Google Calendar is connected.',
        gcalCalendarsCount: (total: number, syncing: number) => `Calendars: ${total} total, ${syncing} syncing.`,
        gcalNoCalendars: 'No Google Calendars found. Sync may still be in progress.',
        gcalList: (lines: string) => `Google Calendars:\n${lines}`,
        userPickerSent: 'User picker sent. Waiting for user to select participants.',
        tableRendering: (title: string) => `Table "${title}" is rendering and will appear in the chat shortly.`,
        tableRenderingVoice: 'Check the chat — the table is there.',
      },
      slots: {
        noFreeSlots: 'No free slots — the entire day is busy.',
        freeSlots: (lines: string) => `Free slots:\n${lines}`,
      },
      settings: {
        callsUpdated: 'Call settings updated.',
        notificationsUpdated: (keys: string) => `Notification settings updated: ${keys}`,
        privacyUpdated: (lines: string) => `Privacy settings updated: ${lines}`,
        voiceUpdated: (value: string) => `Voice settings updated: voice_response_enabled = ${value}`,
      },
      feedback: {
        feedbackSent: 'Feedback sent to developer. They will respond in this chat.',
      },
      events: {
        noEventsInRange: 'No events found in this range.',
        noEventsMatching: 'No events found matching the query.',
        noEventsMatchingScope: (scope: string) =>
          `No events found matching the query in ${scope} calendar. Try searching the other scope.`,
        noUpcomingEvents: 'No upcoming events.',
        upcomingEvents: (count: number, lines: string) => `Next ${count} events:\n${lines}`,
        eventCreated: (parts: string) => `Event created: ${parts}`,
        eventUpdated: (parts: string) => `Event updated: ${parts}`,
        eventDeleted: (title: string, id: number) => `Event "${title}" (id: ${id}) deleted.`,
        eventDeclined: (id: number) =>
          `You declined the shared event (id: ${id}). It has been removed from your calendar.`,
        snoozed: (title: string, minutes: number, newStart: string) =>
          `Event "${title}" snoozed by ${minutes} min. New start: ${newStart}`,
      },
      reminders: {
        noReminders: (title: string) => `No reminders set for "${title}".`,
        remindersSet: (title: string, descriptions: string) => `Reminders set for "${title}": ${descriptions}`,
        remindersDisabled: (title: string) => `All reminders disabled for "${title}".`,
        remindersFor: (title: string, lines: string) => `Reminders for "${title}": ${lines}`,
        durationMin: (n: number) => `${n}min`,
        durationHourMin: (h: number, m: number) => (m > 0 ? `${h}h ${m}m` : `${h}h`),
        beforeDuration: (dur: string) => `${dur} before`,
        noEventsForQuery: (query: string) => `No events found for "${query}".`,
        noRemindersLabel: 'No reminders',
        noRemindersFound: 'No reminders found.',
      },
      sharing: {
        eventShared: (title: string, id: number, targetType: string, targetId: number) =>
          `Event "${title}" shared (id: ${id}, target: ${targetType} ${targetId}).`,
        invitationCreated: (invId: number, eventId: number, inviteeId: number) =>
          `Invitation created (id: ${invId}, event: ${eventId}, invitee: ${inviteeId}). Notification is being sent in background.`,
        invitationCancelled: (id: number) => `Invitation ${id} cancelled.`,
        invitationReminderQueued: (userId: number) =>
          `Invitation reminder queued for user ${userId}. Notification is being sent in background.`,
        noInvitations: (title: string) => `No invitations for event "${title}".`,
        invitationsFor: (title: string, id: number, lines: string) =>
          `Invitations for "${title}" (id: ${id}):\n${lines}`,
        noEventsToShare: (period: string) => `No visible events to share for ${period}.`,
        agendaShared: (period: string, targetType: string, targetId: number, count: number, lines: string) =>
          `Agenda for ${period} shared with ${targetType} ${targetId} (${count} events):\n${lines}`,
        visibilitySet: (title: string, id: number, visibility: string) =>
          `Visibility for "${title}" (id: ${id}) set to "${visibility}".`,
        editProposalSubmitted: (id: number) =>
          `Edit proposal submitted (id: ${id}). The event creator will be notified to accept or reject.`,
      },
      birthdays: {
        created: (name: string, day: number, month: number) =>
          `Birthday created: Bday ${name} (${day}.${String(month).padStart(2, '0')})`,
        alreadyExists: (name: string, day: number, month: number) =>
          `Birthday for ${name} already exists: ${day}.${String(month).padStart(2, '0')}`,
        conflictError: (name: string, day: number, month: number) =>
          `Birthday for ${name} already exists on ${day}.${String(month).padStart(2, '0')}. To update, call again with the correct date.`,
      },
      scheduled: {
        noScheduledCalls: 'No scheduled calls.',
        noTriggers: 'No triggers.',
        scheduleCreated: (id: string, message: string, when: string) =>
          `Scheduled (id: ${id}): "${message}" at ${when}`,
        scheduleCancelled: (id: string) => `Schedule ${id} cancelled.`,
        triggerCreated: (id: string, topic: string, condition: string | null, action: string) =>
          `Trigger created (id: ${id}): when ${topic}${condition ? ` and (${condition})` : ''} → "${action}"`,
        triggerRemoved: (id: string) => `Trigger ${id} removed.`,
      },
      location: {
        clarifyAddress: (title: string) => `📍 Clarify the address for "${title}":`,
        locationResolved: (title: string, address: string) => `📍 Location for "${title}" resolved: ${address}`,
        locationNotFound: (title: string) =>
          `📍 Could not resolve location for "${title}". You can send a 📍 location pin or type the full address.`,
        geoForEvent: (title: string) => `📍 Got your location! Is this for the event "${title}"?`,
        geoForEventConfirm: 'Yes, use for this event',
        geoNewLocation: 'No, this is my current location',
        geoExplain: 'Something else',
        geoOtherAck:
          "📍 Got it. The pin is saved for 30 minutes — just tell me which event it's for and I'll attach it.",
        geoPurposeQuestion:
          '📍 Got your location! What is it for?\n1. Update your current city\n2. Set as location for your latest event\n3. Something else (please explain)',
      },
      agent: {
        connectMessage: (url: string) =>
          `🔗 *Connect AI Assistant*\n\n1\\. [Download the agent](${url})\n2\\. Open the \\.dmg and drag the app to Applications\n3\\. Right\\-click the app → *Open* \\(don't double\\-click\\)\n   _If macOS says "damaged" — run in Terminal:_\n   \`xattr -cr '/Applications/HyperBotAgent.app'\`\n4\\. The app will show an activation command — send it here`,
        activatePrompt: 'Provide the code from the app: /activate <code>',
        activated:
          '✅ Agent connected!\n\nYou can now ask me to run tasks on your Mac:\n• Run terminal commands\n• Chat with Claude Desktop and stream responses\n• Control the browser via Playwright\n• Run AppleScript\n\nJust tell me what to do, e.g. "run ls -la" or "ask Claude what TCP is".',
        activationFailed: '❌ Code not found or expired. Open the app and copy the command again.',
        disconnected: '✅ Agent disconnected. AI assistant disabled.',
        notConnected: 'Agent is not connected.',
        statusConnected: (connectedAt: string, lastPing: string) =>
          `🟢 Agent connected\n\nConnected: ${connectedAt}\nLast ping: ${lastPing}`,
        statusDisconnected:
          '🔴 Agent not running.\n\nStart the HyperBotAgent app on your Mac. If not installed yet — /connect.',
        statusDisabledByUser:
          '⚠️ Agent app is connected but AI assistant tools are disabled.\n\nUse /activate <code> to re-enable.',
      },
    },
    callbackErrors: {
      notFound: 'Not found',
      error: 'Error',
      notAuthorized: 'Not authorized',
      notConfigured: 'Not configured',
      couldNotSendImage: '⚠️ Could not send image',
      renderFailed: '⚠️ Render failed',
      imageGenerationFailed: '⚠️ Image generation failed. Use text version above.',
      proposalNotFound: 'Proposal not found',
      proposalAlreadyProcessed: (status: string) => `Already ${status}`,
      threadNotFound: 'Thread not found',
      threadClosed: 'Thread closed',
      sendReplyMessage: 'Send your reply message',
      intentApproved: '✅ Intent approved',
      intentRejected: '❌ Intent rejected',
      sendEditInstructions: 'Send edit instructions...',
      notYourQuestion: 'Not your question',
      unavailable: 'Unavailable',
      closed: '❌ Closed',
      editCancelled: '❌ Edit cancelled',
      deletionCancelled: '❌ Deletion cancelled',
      disconnectCancelled: '❌ Disconnection cancelled',
      cancelled: '❌ Cancelled',
      invitationCancelled: '❌ Invitation cancelled',
      sentBelow: '✅ Sent below',
      forwardHint: '↗️ Forward this message',
      sceneHelpPrompt: 'AI will help. Just tell me what you need.',
      invitePickContact: (title: string) => `📨 ${title}\nPick a contact:`,
      inviteSelectUser: '👤 Select user',
      inviteSelectGroup: '👥 Select group',
      inviteTapButton: 'Tap button below:',
      inviteSending: '⏳ Sending invitations...',
      proposalAccepted: (title: string) => `✅ Proposal accepted. Event "${title}" updated.`,
      proposalAcceptedNoEvent: '✅ Proposal accepted.',
      proposalRejected: '❌ Proposal rejected.',
      proposalAcceptedNotification: '✅ Your edit proposal was accepted.',
      proposalRejectedNotification: '❌ Your edit proposal was rejected.',
      feedbackThreadResolved: 'Your feedback thread has been resolved.',
      adminReplySent: 'Reply sent.',
      adminReplyDeliveredToGroup: 'Delivered to group (user has not started the bot).',
      adminReplyFailed: '⚠️ Delivery failed — user has not started the bot.',
    },
    notifications: {
      morning: "Good morning! Here's your day:",
      morningFree: 'Good morning!',
      evening: "Tomorrow's schedule:",
      eveningFree: 'Good evening!',
      reminder: 'Reminder:',
      reminders: 'Reminders',
      inLabel: 'in',
      startingNow: 'starting now!',
      eventsCount: (n: number) => `${n} event${n === 1 ? '' : 's'}`,
      goodNight: 'Good night!',
      tomorrow: 'tomorrow',
      haveADay: 'Have a productive day!',
      eveHoliday: (name: string) => `🎉 Tomorrow is a holiday: ${name}`,
      weeklyDigest: (range: string) => `📅 Week ${range}:`,
      noEvents: 'no events',
      allDay: 'All day',
      freeDayMorning:
        'No events today — your day is free!\nWant to plan something? Just describe it in a message, or use /add.',
      freeDayEvening:
        'No events tomorrow — the day is free!\nWant to plan ahead? Just describe it in a message, or use /add.',
      durationHours: (h: number) => `${h}h`,
      durationMinutes: (m: number) => `${m} min`,
      clockChangeForward: (duration: string) =>
        `🕐 Clocks moved ${duration} forward last night. Double-check your alarms and meetings!`,
      clockChangeBack: (duration: string) =>
        `🕐 Clocks moved ${duration} back last night. Double-check your alarms and meetings!`,
    },
    weather: {
      tempCurrent: (current: number, min: number, max: number) => `${current}°C (${min}..${max}°C)`,
      tempRange: (min: number, max: number) => `${min}..${max}°C`,
      wind: (ms: number) => `${ms} m/s`,
      weekForecast: '🌤 Weather this week:',
    },
    botTips: {
      // ── Creating events ──
      voice_create: "💡 Send a voice message to quickly create an event — I'll understand!",
      add_command: '💡 Use /add to create a new event step by step.',
      natural_language: '💡 Just type naturally: "Dentist on Friday at 3pm" — I\'ll create the event.',
      recurring_events: '💡 I can create recurring events — try "standup every weekday at 10am".',
      complex_recurrence: '💡 "Lunch with Anna every other Thursday at 1pm" — I handle complex recurrences too.',
      ics_import: '💡 Import your existing calendar — just send an .ics file to this chat.',
      // ── Reminders & not forgetting ──
      call_before_flight: "💡 Don't want to miss a flight? Add your airport arrival time and ask me to call you!",
      multiple_reminders: '💡 Set multiple reminders: "remind me 1 day and 2 hours before the meeting".',
      voice_calls: '💡 I can call you on the phone before an important event — enable voice calls in /settings.',
      daily_medicine: '💡 "Remind me to take medicine every day at 8am" — I\'ll send a notification daily.',
      birthday_reminder: "💡 Set a reminder for a friend's birthday so you have time to pick a gift.",
      // ── Planning & overview ──
      week_overview: '💡 Ask "what\'s my week look like?" for a quick overview.',
      free_slots: '💡 "When am I free on Wednesday?" — I\'ll find open slots in your schedule.',
      month_view: '💡 Use /month to see a visual calendar of the whole month.',
      meeting_count: '💡 "How many meetings do I have this week?" — I can count and summarize.',
      morning_agenda:
        '💡 Set up a morning agenda to start every day knowing what\'s ahead — "set morning agenda to 7:30".',
      evening_review: '💡 Enable the evening review to prepare for tomorrow — "turn on evening review at 9pm".',
      // ── Sharing & collaboration ──
      share_schedule: '💡 Share your schedule: "share my week with @username" — they\'ll see your events.',
      invite_people: '💡 Invite people to events: "invite @anna to Friday\'s dinner".',
      accept_decline: '💡 When someone sends you an invitation, you can accept, decline, or propose a different time.',
      group_calendar: '💡 Add the bot to a group chat to manage a shared group calendar!',
      secretary_access: "💡 Give a colleague secretary access to manage your calendar when you're busy.",
      // ── Google Calendar ──
      connect_google: '💡 Connect Google Calendar with /connect_google — all your events will sync automatically.',
      google_sync: '💡 After connecting Google, events from all your Google calendars appear here.',
      // ── Life situations: Travel ──
      pack_suitcase:
        '💡 Planning a trip? Add "Pack suitcase" the day before and "Taxi to airport" with the exact time.',
      hotel_checkin: "💡 Add hotel check-in/check-out times to your calendar so you don't miss them.",
      visa_appointment:
        '💡 "Visa appointment on March 15 at 9am, remind me 1 week and 1 day before" — for documents prep.',
      timezone_change: '💡 Crossing time zones? Change your timezone: "set my timezone to America/New_York".',
      // ── Life situations: Health ──
      doctor_checkup: '💡 "Doctor appointment every 6 months" — I\'ll remind you to schedule checkups.',
      gym_sessions: '💡 Track gym sessions: "gym every Mon, Wed, Fri at 7pm" — see how consistent you are.',
      drink_water: '💡 "Remind me to drink water every 2 hours" — health habits as calendar events!',
      // ── Life situations: Work ──
      weekly_oneone: '💡 Weekly 1-on-1? "1-on-1 with manager every Tuesday at 4pm, remind 15 min before".',
      sprint_review: '💡 "Sprint review every other Friday at 3pm" — I handle biweekly schedules.',
      prep_time: '💡 Before a presentation, add prep time: "Prep slides — Friday 2pm to 4pm".',
      event_descriptions: '💡 Use event descriptions to keep meeting agendas and notes organized.',
      // ── Life situations: Personal ──
      anniversary: '💡 Never forget an anniversary — "Wedding anniversary every year on June 15".',
      movie_premieres: "💡 Add movie premieres, concert dates, or game releases you're excited about.",
      rent_payment: '💡 "Rent payment every month on the 1st" — financial deadlines stay on track.',
      subscriptions: '💡 Track subscriptions: "Netflix renewal every month on the 12th" — know when charges hit.',
      reading_challenge: '💡 Reading challenge? "Read for 30 min every evening at 9pm" — build a habit.',
      // ── Life situations: Family ──
      family_calendar: '💡 Share your family calendar in a group chat — everyone sees school events and activities.',
      kids_swimming: '💡 "Kids swimming class every Saturday at 10am" — family routines made easy.',
      school_events: '💡 Add school parent meetings, picture days, and holidays to the group calendar.',
      // ── Life situations: Social ──
      birthday_party: '💡 "Birthday party for Max — Saturday 6pm at The Pub" — then invite friends from contacts.',
      decline_propose:
        "💡 Can't make it? Decline an invitation and propose a better time — the organizer gets notified.",
      find_free_time: '💡 Use /free to find a time that works: "when am I free this Saturday afternoon?"',
      // ── Power features ──
      context_awareness: '💡 I remember context — say "move it to 3pm" and I\'ll know which event you mean.',
      automated_reminders: '💡 Schedule automated messages: "remind me every Friday at 5pm to submit timesheets".',
      public_holidays: "💡 Use /holidays to subscribe to public holidays — they'll appear in your calendar.",
      save_contacts: '💡 Save contacts (/contacts) and invite them to events by name — no need for usernames.',
      quiet_hours: "💡 Set up quiet hours so I don't disturb you at night — check /settings.",
      language_switch: '💡 I speak Russian and English — switch language anytime in /settings.',
      action_log: '💡 Send /log to see a full history of actions taken on your calendar.',
      past_events: '💡 "What did I have last Tuesday?" — I can look up past events too.',
    },
    gtdQuotes: [
      // David Allen, "Getting Things Done: The Art of Stress-Free Productivity" (2001/2015)
      // Quotes verified across multiple public sources (Goodreads, GTD Forums, official site)
      '📖 "Your mind is for having ideas, not holding them." — David Allen, GTD, ch. 1',
      '📖 "If you don\'t pay appropriate attention to what has your attention, it will take more of your attention than it deserves." — David Allen, GTD, ch. 2',
      '📖 "Your ability to generate power is directly proportional to your ability to relax." — David Allen, GTD, ch. 1',
      '📖 "You don\'t actually do a project; you can only do action steps related to it." — David Allen, GTD, ch. 3',
      '📖 "Much of the stress that people feel doesn\'t come from having too much to do. It comes from not finishing what they\'ve started." — David Allen, GTD, ch. 6',
      '📖 "It is easier to act yourself into a better way of feeling than to feel yourself into a better way of action." — David Allen, GTD, ch. 12',
      '📖 "Most people feel best about their work the week before their vacation, but it\'s not because of the vacation itself. What do you do the last week before you leave on a big trip? You clean up, close up, clarify, and renegotiate all your agreements with yourself and others. I just suggest that you do this weekly instead of yearly." — David Allen, GTD, ch. 8',
      '📖 "There is usually an inverse relationship between how much something is on your mind and how much it\'s getting done." — David Allen, GTD, ch. 1',
      '📖 "You can only feel good about what you\'re not doing when you know what you\'re not doing." — David Allen, GTD, ch. 9',
      "📖 \"Anything that does not belong where it is, the way it is, is an 'open loop,' which will be pulling on your attention if it's not appropriately managed.\" — David Allen, GTD, ch. 2",
      "📖 \"Getting things done requires two basic components: defining (1) what 'done' means (outcome) and (2) what 'doing' looks like (action).\" — David Allen, GTD, ch. 2",
      '📖 "Your head is for having ideas, not for holding them. That\'s what a trusted system is for." — David Allen, GTD, ch. 4',
      '📖 "The two-minute rule: if the next action can be done in two minutes or less, do it when you first pick the item up." — David Allen, GTD, ch. 6',
      '📖 "Think like a man of action, act like a man of thought." — Henri Bergson, quoted in GTD, ch. 3',
      '📖 "The big secret to efficient creative and productive thinking and action is to put the right things in your focus at the right time." — David Allen, GTD, ch. 9',
      '📖 "One of the best tricks for enhancing your productivity is having organized, ready-to-review action reminders." — David Allen, GTD, ch. 7',
      '📖 "The Weekly Review is the time to gather and process all your stuff, review your system, update your lists, and get clean, clear, current, and complete." — David Allen, GTD, ch. 8',
      '📖 "A great hammer doesn\'t make a great carpenter; but a great carpenter will always want to have a great hammer." — David Allen, GTD, ch. 5',
    ],
    atomicHabitsQuotes: [
      // James Clear, "Atomic Habits" (2018)
      '📖 "You do not rise to the level of your goals. You fall to the level of your systems." — James Clear, Atomic Habits, ch. 1',
      '📖 "Every action you take is a vote for the type of person you wish to become." — James Clear, Atomic Habits, ch. 2',
      '📖 "Habits are the compound interest of self-improvement." — James Clear, Atomic Habits, ch. 1',
      '📖 "The most effective way to change your habits is to focus not on what you want to achieve, but on who you wish to become." — James Clear, Atomic Habits, ch. 2',
      '📖 "Be the designer of your world and not merely the consumer of it." — James Clear, Atomic Habits, ch. 6',
      '📖 "When you fall in love with the process rather than the product, you don\'t have to wait to give yourself permission to be happy." — James Clear, Atomic Habits, ch. 1',
      '📖 "The task of breaking a bad habit is like uprooting a powerful oak within us." — James Clear, Atomic Habits, ch. 7',
      '📖 "Success is the product of daily habits — not once-in-a-lifetime transformations." — James Clear, Atomic Habits, ch. 1',
      '📖 "Time magnifies the margin between success and failure. It will multiply whatever you feed it." — James Clear, Atomic Habits, ch. 1',
      '📖 "You should be far more concerned with your current trajectory than with your current results." — James Clear, Atomic Habits, ch. 1',
      '📖 "The purpose of setting goals is to win the game. The purpose of building systems is to continue playing the game." — James Clear, Atomic Habits, ch. 1',
      '📖 "Missing once is an accident. Missing twice is the start of a new habit." — James Clear, Atomic Habits, ch. 16',
    ],
    deepWorkQuotes: [
      // Cal Newport, "Deep Work: Rules for Focused Success in a Distracted World" (2016)
      '📖 "If you don\'t produce, you won\'t thrive — no matter how skilled or talented you are." — Cal Newport, Deep Work, ch. 1',
      '📖 "Clarity about what matters provides clarity about what does not." — Cal Newport, Deep Work, ch. 4',
      '📖 "The ability to perform deep work is becoming increasingly rare at exactly the same time it is becoming increasingly valuable." — Cal Newport, Deep Work, intro',
      '📖 "Two core abilities for thriving in the new economy: the ability to quickly master hard things, and the ability to produce at an elite level." — Cal Newport, Deep Work, ch. 1',
      '📖 "Who you are, what you think, feel, and do, what you love — is the sum of what you focus on." — Cal Newport, Deep Work, ch. 3',
      '📖 "A deep life is a good life, any way you look at it." — Cal Newport, Deep Work, conclusion',
      '📖 "Efforts to deepen your focus will struggle if you don\'t simultaneously wean your mind from a dependence on distraction." — Cal Newport, Deep Work, rule 2',
      '📖 "The key to developing a deep work habit is to move beyond good intentions and add routines and rituals to your working life." — Cal Newport, Deep Work, rule 1',
      '📖 "Treat your time with respect. Schedule every minute of your day." — Cal Newport, Deep Work, rule 4',
      '📖 "Don\'t take breaks from distraction. Instead take breaks from focus." — Cal Newport, Deep Work, rule 2',
    ],
    sevenHabitsQuotes: [
      // Stephen R. Covey, "The 7 Habits of Highly Effective People" (1989)
      '📖 "The key is not to prioritize what\'s on your schedule, but to schedule your priorities." — Stephen Covey, 7 Habits, habit 3',
      '📖 "Begin with the end in mind." — Stephen Covey, 7 Habits, habit 2',
      '📖 "Put first things first." — Stephen Covey, 7 Habits, habit 3',
      '📖 "Most of us spend too much time on what is urgent and not enough time on what is important." — Stephen Covey, 7 Habits, habit 3',
      '📖 "The main thing is to keep the main thing the main thing." — Stephen Covey, 7 Habits, habit 3',
      '📖 "Sow a thought, reap an action; sow an action, reap a habit; sow a habit, reap a character; sow a character, reap a destiny." — Stephen Covey, 7 Habits, habit 1',
      '📖 "Between stimulus and response there is a space. In that space is our freedom and power to choose our response." — Stephen Covey, 7 Habits, habit 1',
      '📖 "Be proactive. Highly effective people don\'t just react to circumstances — they create them." — Stephen Covey, 7 Habits, habit 1',
      '📖 "Seek first to understand, then to be understood." — Stephen Covey, 7 Habits, habit 5',
      '📖 "Live out of your imagination, not your history." — Stephen Covey, 7 Habits, habit 2',
    ],
    contextualTips: {
      noEveningReview:
        '💡 Your mornings are set — how about evenings? Enable the evening review to prepare for tomorrow: "turn on evening review at 9pm".',
      noMorningAgenda:
        '💡 Want to start each day with a plan? Enable the morning agenda: "set morning agenda to 7:30".',
      noQuietHours: "💡 Protect your sleep — set up quiet hours so I don't disturb you at night. Check /settings.",
      noGoogleCalendar: '💡 Connect Google Calendar to see all your events in one place — /connect_google.',
      noCountry: '💡 Set your country to get public holidays in your calendar — /holidays.',
      noVoiceCalls:
        '💡 I can call you before important events so you never miss them. Enable voice calls in /settings.',
    },
    speech: {
      allDay: 'all day',
      noEvents: 'no events',
      at: 'at',
      morningIntro: (dateLabel: string) => `Good morning. Today, ${dateLabel}.`,
      morningOutro: 'Have a productive day!',
      eveningIntro: (dateLabel: string) => `Good evening. Tomorrow, ${dateLabel}.`,
      eveningOutro: 'Good night!',
      weeklyDigestIntro: (weekRange: string) => `Weekly digest for the week of ${weekRange}.`,
      reminderIntro: (cleanTitle: string, timeStr: string) => `Calendar reminder. ${cleanTitle} at ${timeStr}.`,
      location: (loc: string) => `Location: ${loc}.`,
      batchIntro: (count: number) => `Calendar reminder. ${count} ${count === 1 ? 'event' : 'events'} starting soon:`,
      eventAt: (title: string, timeStr: string) => `${title} at ${timeStr}.`,
    },
  },
  ru: {
    welcome: '🌍 Choose your language / Выберите язык:',
    tz_prompt: 'Установим часовой пояс. Самый точный способ — поделиться геолокацией.',
    tz_detected: (tz: string, offset: string) => `Ваш часовой пояс: ${tz} (${offset}).\nВсё верно?`,
    tz_confirm_yes: 'Да ✓',
    tz_confirm_no: 'Нет, выбрать вручную',
    geo_tz_confirm_prompt: (currentTz: string, newTz: string, offset: string) =>
      `📍 Твой текущий часовой пояс — <b>${currentTz}</b>.\nПо геолокации похоже, что ты в <b>${newTz}</b> (${offset}).\n\nОбновление часового пояса нужно, чтобы напоминания, сводка дня и время событий отображались правильно.\n\nОбновить часовой пояс?`,
    geo_tz_confirm_btn: 'Да, обновить ✓',
    geo_tz_dismiss_btn: 'Нет, оставить',
    geo_tz_updated: (tz: string, offset: string) => `✅ Часовой пояс обновлён: ${tz} (${offset}).`,
    geo_tz_dismissed: 'ОК, часовой пояс не изменён.',
    tz_same_from_location: (tz: string, offset: string) =>
      `📍 Твой часовой пояс уже ${tz} (${offset}) — менять ничего не нужно.`,
    share_location: '📍 Отправить геолокацию',
    choose_manually: '⌨️ Выбрать вручную',
    country_prompt: 'Показывать государственные праздники в календаре?',
    country_skip: 'Пропустить',
    agenda_prompt: 'Могу отправлять утреннюю сводку событий на день.\n\nВыберите время для утренней сводки:',
    onboard_done:
      '✅ Всё готово!\n\n/add — создать событие\n/today — расписание на сегодня\n\nПросто напишите или отправьте голосовое — я понимаю естественный язык и могу создавать, редактировать, искать события за вас.',
    no_events_today: (date: string) =>
      `📅 ${date}\n\nНет событий. Хочешь что-то запланировать? Просто напиши сообщение, или используй /add.`,
    no_events: 'Нет событий за этот период.',
    event_created: (title: string) => `✅ Создано: "${title}"`,
    event_deleted: (title: string) => `🗑 Удалено: "${title}"`,
    event_updated: (title: string) => `✏️ Обновлено: "${title}"`,
    confirm_delete: (title: string) => `Удалить "${title}"?`,
    search_no_results: 'Ничего не найдено.',
    something_wrong: 'Что-то пошло не так. Попробуйте ещё раз или /help.',
    rate_limited: 'Слишком много сообщений, подождите.',
    add_title_prompt: 'Создаём событие. Как назовём?',
    add_time_prompt: 'Когда? (например, "завтра 18:00", "15 мар 19:30")',
    add_duration_prompt: 'Сколько длится? (например, "1ч", "30м") или пропустите.',
    add_description_prompt: 'Описание? (текст или "пропустить")',
    add_location_prompt: 'Место? (текст или "пропустить")',
    edit_pick: 'Какое событие редактировать?',
    delete_pick: 'Какое событие удалить?',
    free_header: (date: string) => `📋 Свободные слоты ${date}:`,
    pong: (ms: number) => `понг (${ms}мс)`,
    welcome_back: 'С возвращением! Напишите мне или /help.',
    recurrence_prompt: 'Повторять событие?',
    recurrence_end_prompt: 'Когда прекратить повторение?',
    recurrence_custom_prompt: 'Опишите повторение (напр. "каждые 2 недели", "ежедневно"):',
    recurrence_until_prompt: 'Отправьте дату окончания (напр. "30 мар", "15 января"):',
    recurrence_count_prompt: 'Сколько раз?',
    skip: 'Пропустить',
    holidays_menu: '🌍 <b>Праздники</b>',
    holidays_no_subs: 'Нет подписок. Нажмите "+ Добавить" чтобы подписаться.',
    holidays_added: (country: string) => `✅ Подписка на ${country}`,
    holidays_removed: (country: string) => `Удалено: ${country}`,
    holidays_set_primary: (country: string) => `${country} — основная страна`,
    holidays_pick_region: 'Выберите регион:',
    holidays_pick_country: 'Выберите страну:',
    holidays_upcoming: '📅 <b>Ближайшие праздники</b>',
    holidays_none_upcoming: 'Нет ближайших праздников по вашим подпискам.',
    holidays_day_off: '🎉 Выходной!',
    holidays_manage_prompt: 'Выберите подписку для управления:',
    holidays_notify_on: (country: string) => `${country}: уведомления ВКЛ`,
    holidays_notify_off: (country: string) => `${country}: уведомления ВЫКЛ`,
    ai_error: 'ИИ временно недоступен. Используйте команды бота (/help).',
    ai_clear_history: 'История чата очищена.',
    scene_help_btn: '🆘 Позвать на помощь',
    notify_menu: '⚙️ Настройки уведомлений',
    notify_morning: '🌅 Утренняя повестка',
    notify_morning_status: (enabled: boolean, time: string) => `Утренняя повестка: ${enabled ? `✅ ${time}` : '❌'}`,
    notify_evening: '🌙 Вечерний обзор',
    notify_evening_status: (enabled: boolean, time: string) => `Вечерний обзор: ${enabled ? `✅ ${time}` : '❌'}`,
    notify_reminders: '⏰ Напоминания по умолчанию',
    notify_quiet: '🔇 Тихие часы',
    notify_quiet_status: (enabled: boolean, start: string, end: string) =>
      `Тихие часы: ${enabled ? `✅ ${start} — ${end}` : '❌'}`,
    notify_pick_hour: 'Выберите час:',
    notify_pick_minute: 'Выберите минуту:',
    notify_updated: 'Настройки обновлены',
    notify_intervals_label: (intervals: number[]) =>
      `Напоминания: ${intervals.map((m) => (m === 0 ? 'в начале' : m >= 60 ? `${m / 60}ч` : `${m}мин`)).join(', ')}`,
    gcal_onboarding:
      'Хотите синхронизировать с Google Calendar?\n\nСобытия останутся в боте в любом случае. Синхронизация даёт:\n- Просмотр событий бота в Google Calendar\n- Изменения в Google Calendar авто-синхронизируются\n- Двусторонняя синхронизация',
    gcal_onboarding_maybe_later: 'Позже',
    gcal_not_configured: 'Синхронизация с Google Calendar не настроена. Обратитесь к администратору.',
    gcal_already_connected: 'Google Calendar уже подключён. Используйте /disconnect_google чтобы переподключить.',
    gcal_connect_prompt: '🔗 Подключите Google Calendar для двусторонней синхронизации событий.',
    gcal_connect_button: 'Подключить Google Calendar',
    gcal_connected: '✅ Google Calendar подключён! Выберите календари для синхронизации.',
    gcal_disconnected: '✅ Google Calendar отключён. Локальные события сохранены.',
    gcal_disconnect_confirm: 'Отключить Google Calendar? События останутся в боте.',
    gcal_disconnect_yes: 'Да, отключить',
    gcal_disconnect_no: 'Отмена',
    gcal_calendar_picker: 'Выберите календари для синхронизации (нажмите для переключения):',
    gcal_calendar_done: 'Готово ✓',
    gcal_calendar_readonly: '(только чтение)',
    gcal_calendars_saved: '✅ Выбор сохранён. Начинается синхронизация...',
    gcal_sync_complete: '✅ Синхронизация завершена. Ваши события из Google теперь в боте.',
    gcal_revoked: '⚠️ Связь с Google Calendar потеряна. Используйте /connect_google чтобы переподключить.',
    gcal_conflict: (title: string, winner: string) =>
      `⚠️ Конфликт синхронизации "${title}"\n\n${winner === 'google' ? 'Google Calendar' : 'Локальная'} версия применена (более новая).`,
    gcal_status_connected: 'Подключён ✅',
    gcal_status_not_connected: 'Google Calendar не подключён. Используй /connect_google чтобы начать синхронизацию.',
    gcal_status_sync_btn: '🔄 Синхронизировать',
    gcal_status_calendars_btn: '⚙️ Календари',
    gcal_status_sync_started: '⏳ Синхронизация запущена',
    invite_error: 'Не удалось отправить приглашение.',
    invite_delivered: (title: string) => `📨 Приглашение на "<b>${title}</b>" отправлено`,
    invite_deep_link: (title: string, url: string) =>
      `Пользователь ещё не запустил бота. Перешлите ссылку для принятия:\n\n${url}\n\n(Приглашение на "<b>${title}</b>")`,
    invitation_sent: 'Приглашение отправлено',
    invitation_received: (title: string, from: string) =>
      `📨 <b>Приглашение</b>\n${from} приглашает вас: <b>${title}</b>`,
    invitation_accepted: '✅ Приглашение принято',
    invitation_declined: '❌ Приглашение отклонено',
    invitation_maybe: '🤔 Отмечено как "возможно"',
    invitation_cancelled: 'Приглашение отменено',
    invitation_expired: 'Это приглашение истекло',
    invitation_not_found: 'Приглашение не найдено',
    invitation_already_sent: 'Приглашение уже отправлено этому пользователю',
    invitations_disabled: 'Этот пользователь отключил приглашения',
    invitation_response_accepted: (name: string, title: string) =>
      `📨 ${name} принял(а) приглашение на "<b>${title}</b>" ✅`,
    invitation_response_declined: (name: string, title: string) =>
      `📨 ${name} отклонил(а) приглашение на "<b>${title}</b>" ❌`,
    invitation_response_maybe: (name: string, title: string) =>
      `📨 ${name} ответил(а) "возможно" на приглашение "<b>${title}</b>" 🤔`,
    invite_propose_btn: 'Другое время 🕐',
    invite_propose_ask: 'Какое время предлагаешь?\nИли напиши: "завтра в 15:00"',
    invite_propose_plus30: '+30 мин',
    invite_propose_plus60: '+1 час',
    invite_propose_sent: (time: string) => `⏰ Вы предложили: ${time}`,
    invite_propose_notify: (name: string, event: string, time: string) =>
      `📅 ${name} предлагает перенести <b>${event}</b> на ${time}`,
    invite_reschedule_btn: 'Перенести 📅',
    invite_keep_btn: 'Оставить как есть',
    invite_rescheduled_inviter: (time: string) => `✅ Событие перенесено на ${time}`,
    invite_rescheduled_invitee: (event: string, time: string) =>
      `✅ <b>${event}</b> перенесено на ${time}. Вы автоматически приняты.`,
    invite_kept_inviter: '❌ Предложение отклонено',
    invite_kept_invitee: (event: string, time: string) =>
      `❌ Ваше предложение для <b>${event}</b> отклонено. Событие остаётся в ${time}.`,
    invitations_from: (name: string) => `от ${name}`,
    invitations_to: (name: string) => `для ${name}`,
    privacy_current: (level: string) => `🔒 Текущая видимость: <b>${level}</b>`,
    share_preview: '📤 Превью — вот что будет отправлено:',
    share_sent: '✅ Отправлено',
    share_cancelled: '❌ Отправка отменена',
    no_events_to_share: 'Нет событий для этого периода',
    call_settings_title: '📞 Голосовые напоминания',
    call_settings_enabled: 'Голосовые звонки: ✅ Включены',
    call_settings_disabled: 'Голосовые звонки: ❌ Выключены',
    call_post_snooze: '⏰ Отложено на 10 мин',
    call_post_cancel: '❌ Событие отменено',
    call_post_ack: '✅ Понятно',
    voice_response_enabled: '🎤 Голосовые ответы включены!',
    voice_response_disabled: '🎤 Ок, только текстом.',
    voice_demo_failed: '🎤 Голосовые ответы включены! Демо не воспроизвелось — голос появится со следующего ответа.',
    cancelled: 'Отменено.',
    voice_prompt: '🎤 Хочешь получать голосовые ответы?\nУдобно за рулём, на кухне или на ходу.',
    voice_prompt_yes: 'Да, хочу',
    voice_prompt_no: 'Нет, только текстом',
    voice_stt_error: 'Не удалось распознать речь.',
    voice_error: 'Не удалось обработать голосовое сообщение.',
    group_event_created: (groupRef: string, organizerLink: string) =>
      `📅 Новое событие в ${groupRef}\n👤 Организатор: ${organizerLink}`,
    group_event_updated: (groupRef: string, organizerLink: string) =>
      `✏️ Событие обновлено в ${groupRef}\n👤 Изменил: ${organizerLink}`,
    feature_tour_btn: '📖 Все функции',
    feature_tour: [
      '<b>🤖 AI-ассистент</b>\nПросто напишите или отправьте голосовое: "запланируй встречу завтра в 15:00", "что у меня на неделе?", "перенеси стендап на 11:00". Все функции бота доступны через чат — я понимаю контекст и выполняю команды.',
      '<b>📅 Управление календарём</b>\n/add — пошаговое создание\n/today, /week, /month — разные виды\n/edit, /delete — редактирование\n/free — свободные слоты\nПовторяющиеся события с гибкими правилами.',
      '<b>🔔 Умные напоминания</b>\n/settings — утренняя сводка, вечерний обзор, тихие часы, голосовые звонки, приватность\nНесколько напоминаний на событие (15 мин, 1 ч и т.д.)',
      '<b>🌍 Праздники</b>\n/holidays — подписка на праздники 100+ стран\nПраздники отображаются в ежедневной повестке.',
      '<b>📤 Шаринг и приглашения</b>\n/share today — поделиться расписанием\n/invite @username — пригласить на событие\nВидимость событий: /settings → Приватность\nInline-режим: наберите @HyperCalendarBot в любом чате.',
      '<b>🖼 Визуальное расписание</b>\nКрасивые изображения календаря автоматически отправляются с командами /today и /week.',
    ],
    settings: {
      title: '⚙️ Настройки',
      back: '🔙 Назад',
      close: '✖️ Закрыть',
      categoryGeneral: '🌍 Основные',
      categoryNotifications: '🔔 Уведомления',
      categoryCalls: '📞 Звонки',
      categoryPrivacy: '🔒 Приватность',
      categoryVoice: '🎤 Голос',
      notificationsTitle: '🔔 Уведомления',
      morningAgenda: 'Утренняя сводка',
      morningAgendaDesc: 'Краткая повестка дня отправляется каждое утро.',
      eveningReview: 'Вечерний обзор',
      eveningReviewDesc: 'Список событий на завтра — удобно проверить перед сном.',
      quietHours: 'Тихие часы',
      quietHoursDesc: 'Напоминания и звонки не беспокоят в это время.',
      reminders: 'Напоминания',
      remindersDesc: 'За сколько до события бот присылает напоминание.',
      toggleMorning: 'Утренняя сводка',
      toggleEvening: 'Вечерний обзор',
      toggleQuiet: 'Тихие часы',
      editReminders: '⏰ Интервалы напоминаний',
      reminderIntervalsTitle: '⏰ Интервалы напоминаний',
      reminderIntervalsActive: (intervals: string) => `Активные: ${intervals}`,
      reminderIntervalsNone: 'не заданы',
      reminderIntervalsHint: 'Выберите за сколько до события отправлять напоминание.',
      reminderAtStart: 'в начале',
      callsTitle: '📞 Голосовые звонки',
      callsEnabled: 'Звонки-напоминания: ✅ Включены',
      callsDisabled: 'Звонки-напоминания: ❌ Отключены',
      callsDesc1: 'Бот позвонит вам перед событием и зачитает название.',
      callsDesc2: 'Работает через Telegram-звонок — не нужен номер телефона.',
      callsDesc3: 'Тихие часы распространяются и на звонки.',
      toggleCallsEnable: '✅ Включить звонки',
      toggleCallsDisable: '❌ Отключить звонки',
      privacyTitle: '🔒 Приватность',
      visibilityLabel: 'Видимость событий',
      visibilityPrivate: 'Приватно',
      visibilityFreeBusy: 'Занят/свободен',
      visibilityFull: 'Полный доступ',
      visibilityPrivateDesc: 'Только вы видите свои события.',
      visibilityFreeBusyDesc: 'Другие видят что вы заняты, но не что именно.',
      visibilityFullDesc: 'Другие видят названия и детали ваших событий.',
      inlineSearch: 'Инлайн-поиск',
      inlineSearchDesc: 'Позволяет @HyperCalendarBot находить вас через inline-режим.',
      invitations: 'Приглашения',
      invitationsDesc: 'Разрешить другим пользователям приглашать вас на события.',
      cycleVisibility: (label: string) => `👁 Видимость: ${label} →`,
      voiceTitle: '🎤 Голосовые ответы',
      voiceStatus: 'Голосовые ответы',
      voiceNotSet: '❓ Не задано',
      voiceEnabled: '✅ Включены',
      voiceDisabled: '❌ Отключены',
      voiceDesc1: 'Когда включено — бот отвечает на сообщения голосом (TTS).',
      voiceDesc2: 'Работает на русском и английском в зависимости от языка бота.',
      voiceDesc3: 'Текстовый ответ отправляется всегда, голос — дополнительно.',
      toggleVoiceEnable: '✅ Включить голосовые ответы',
      toggleVoiceDisable: '❌ Отключить голосовые ответы',
      showCountries: '🏳️ Выберите страну:',
    },
    aiTools: {
      history: {
        notFound: 'История не найдена.',
      },
      actionLog: {
        notFound: 'Записей в логе действий не найдено.',
      },
      meta: {
        noHolidays: 'Праздников не найдено. Возможно, у тебя не настроены подписки на страны.',
        unknownName: 'неизвестно',
        holidaysList: (lines: string) => `Праздники:\n${lines}`,
        foundUser: (id: number, name: string) => `Пользователь найден: telegram_id=${id}, имя=${name}`,
        foundUserMtproto: (id: number, name: string) =>
          `Пользователь найден через MTProto: telegram_id=${id}, имя=${name} (бот ещё не запускал — доступен только через MTProto)`,
        addressBookEmpty: 'Адресная книга пуста.',
        contactsList: (lines: string) => `Контакты:\n${lines}`,
        contactSaved: (name: string) => `Контакт сохранён: ${name}`,
        contactFound: (data: string) => `Контакт найден: ${data}`,
        contactUpdated: (label: string) => `Контакт обновлён: ${label}`,
        questionSent: 'Вопрос отправлен. Ожидаю ответа.',
        dayImageRendering: (date: string) => `Изображение за ${date} формируется и будет отправлено фото.`,
        weekImageRendering: (weekStart: string) =>
          `Недельный календарь с ${weekStart} формируется и будет отправлен фото.`,
        monthImageRendering: (month: string) => `Месячный календарь за ${month} формируется и будет отправлен фото.`,
        callQueued: 'Звонок поставлен в очередь. Ты получишь голосовой звонок в ближайшее время.',
        callFailed: (text: string) => `📞 Не удалось дозвониться.\n\n${text}`,
        gcalNotConnected: 'Google Calendar не подключён. Ты можешь подключить его командой /connect_google.',
        gcalConnectedNoData: 'Google Calendar подключён, но данные календарей недоступны.',
        gcalConnectedHeader: 'Google Calendar подключён.',
        gcalCalendarsCount: (total: number, syncing: number) =>
          `Календари: всего ${total}, синхронизируется ${syncing}.`,
        gcalNoCalendars: 'Google-календари не найдены. Возможно, синхронизация ещё идёт.',
        gcalList: (lines: string) => `Google-календари:\n${lines}`,
        userPickerSent: 'Форма выбора участников отправлена. Ожидаю ответа.',
        tableRendering: (title: string) => `Таблица «${title}» рендерится и скоро появится в чате.`,
        tableRenderingVoice: 'Загляни в чат — там таблица.',
      },
      slots: {
        noFreeSlots: 'Свободных окон нет — весь день занят.',
        freeSlots: (lines: string) => `Свободные слоты:\n${lines}`,
      },
      settings: {
        callsUpdated: 'Настройки звонков обновлены.',
        notificationsUpdated: (keys: string) => `Настройки уведомлений обновлены: ${keys}`,
        privacyUpdated: (lines: string) => `Настройки приватности обновлены: ${lines}`,
        voiceUpdated: (value: string) => `Настройки голоса обновлены: voice_response_enabled = ${value}`,
      },
      feedback: {
        feedbackSent: 'Отзыв отправлен разработчику. Ответ придёт в этот чат.',
      },
      events: {
        noEventsInRange: 'Событий в этом диапазоне не найдено.',
        noEventsMatching: 'Событий по запросу не найдено.',
        noEventsMatchingScope: (scope: string) =>
          `Событий по запросу не найдено в ${scope === 'personal' ? 'личном' : 'групповом'} календаре. Попробуй поискать в ${scope === 'personal' ? 'групповом' : 'личном'}.`,
        noUpcomingEvents: 'Предстоящих событий нет.',
        upcomingEvents: (count: number, lines: string) => `Следующие ${count}:\n${lines}`,
        eventCreated: (parts: string) => `Событие создано: ${parts}`,
        eventUpdated: (parts: string) => `Событие обновлено: ${parts}`,
        eventDeleted: (title: string, id: number) => `Событие «${title}» (id: ${id}) удалено.`,
        eventDeclined: (id: number) => `Ты отклонил(а) общее событие (id: ${id}). Оно удалено из твоего календаря.`,
        snoozed: (title: string, minutes: number, newStart: string) =>
          `Событие «${title}» отложено на ${minutes} мин. Новое начало: ${newStart}`,
      },
      reminders: {
        noReminders: (title: string) => `Для «${title}» нет напоминаний.`,
        remindersSet: (title: string, descriptions: string) =>
          `Напоминания для «${title}» установлены: ${descriptions}`,
        remindersDisabled: (title: string) => `Все напоминания для «${title}» отключены.`,
        remindersFor: (title: string, lines: string) => `Напоминания для «${title}»: ${lines}`,
        durationMin: (n: number) => `${n}мин`,
        durationHourMin: (h: number, m: number) => (m > 0 ? `${h}ч ${m}мин` : `${h}ч`),
        beforeDuration: (dur: string) => `за ${dur}`,
        noEventsForQuery: (query: string) => `По запросу «${query}» событий не найдено.`,
        noRemindersLabel: 'Без напоминаний',
        noRemindersFound: 'Напоминаний не найдено.',
      },
      sharing: {
        eventShared: (title: string, id: number, targetType: string, targetId: number) =>
          `Событие «${title}» опубликовано (id: ${id}, получатель: ${targetType} ${targetId}).`,
        invitationCreated: (invId: number, eventId: number, inviteeId: number) =>
          `Приглашение создано (id: ${invId}, событие: ${eventId}, приглашённый: ${inviteeId}). Уведомление отправляется в фоне.`,
        invitationCancelled: (id: number) => `Приглашение ${id} отменено.`,
        invitationReminderQueued: (userId: number) =>
          `Напоминание о приглашении поставлено в очередь (пользователь ${userId}). Уведомление отправляется в фоне.`,
        noInvitations: (title: string) => `Для события «${title}» нет приглашений.`,
        invitationsFor: (title: string, id: number, lines: string) =>
          `Приглашения для «${title}» (id: ${id}):\n${lines}`,
        noEventsToShare: (period: string) => `Нет видимых событий для публикации за ${period}.`,
        agendaShared: (period: string, targetType: string, targetId: number, count: number, lines: string) =>
          `Расписание (${period}) опубликовано для ${targetType} ${targetId} (${count} событий):\n${lines}`,
        visibilitySet: (title: string, id: number, visibility: string) =>
          `Видимость «${title}» (id: ${id}) изменена на «${visibility}».`,
        editProposalSubmitted: (id: number) =>
          `Предложение изменений отправлено (id: ${id}). Создатель события получит уведомление.`,
      },
      birthdays: {
        created: (name: string, day: number, month: number) =>
          `День рождения создан: Д/р ${name} (${day}.${String(month).padStart(2, '0')})`,
        alreadyExists: (name: string, day: number, month: number) =>
          `День рождения ${name} уже есть: ${day}.${String(month).padStart(2, '0')}`,
        conflictError: (name: string, day: number, month: number) =>
          `Уже есть день рождения для ${name}: дата ${day}.${String(month).padStart(2, '0')}. Хочешь обновить?`,
      },
      scheduled: {
        noScheduledCalls: 'Запланированных вызовов нет.',
        noTriggers: 'Триггеров нет.',
        scheduleCreated: (id: string, message: string, when: string) =>
          `Запланировано (id: ${id}): «${message}» — ${when}`,
        scheduleCancelled: (id: string) => `Расписание ${id} отменено.`,
        triggerCreated: (id: string, topic: string, condition: string | null, action: string) =>
          `Триггер создан (id: ${id}): когда ${topic}${condition ? ` и (${condition})` : ''} → «${action}»`,
        triggerRemoved: (id: string) => `Триггер ${id} удалён.`,
      },
      location: {
        clarifyAddress: (title: string) => `📍 Уточни адрес для «${title}»:`,
        locationResolved: (title: string, address: string) => `📍 Адрес для «${title}» определён: ${address}`,
        locationNotFound: (title: string) =>
          `📍 Не удалось определить адрес для «${title}». Можешь отправить 📍 геолокацию или написать полный адрес.`,
        geoForEvent: (title: string) => `📍 Получена геолокация! Это для события «${title}»?`,
        geoForEventConfirm: 'Да, использовать для этого события',
        geoNewLocation: 'Нет, это моё текущее местоположение',
        geoExplain: 'Другое',
        geoOtherAck:
          '📍 Понял. Пин сохранён на 30 минут — просто скажи, к какому событию его привязать, и я сделаю это.',
        geoPurposeQuestion:
          '📍 Получена геолокация! Для чего она?\n1. Обновить город\n2. Задать локацию для последнего события\n3. Другое (напиши пояснение)',
      },
      agent: {
        connectMessage: (url: string) =>
          `🔗 *Подключить AI Ассистент*\n\n1\\. [Скачать агент](${url})\n2\\. Открой \\.dmg и перетащи приложение в Программы\n3\\. Открой приложение правой кнопкой → *Открыть* \\(не двойным кликом\\)\n   _Если macOS пишет «повреждён» — выполни в Терминале:_\n   \`xattr -cr '/Applications/HyperBotAgent.app'\`\n4\\. Приложение покажет команду активации — отправь её сюда`,
        activatePrompt: 'Укажи код из приложения: /activate <код>',
        activated:
          '✅ Агент подключён!\n\nТеперь можешь просить меня выполнять задачи прямо на твоём Mac:\n• Запускать команды в терминале\n• Общаться с Claude Desktop и получать ответы\n• Управлять браузером через Playwright\n• Выполнять AppleScript\n\nПросто напиши что нужно, например: «запусти ls -la» или «спроси Claude что такое TCP».',
        activationFailed: '❌ Код не найден или истёк. Открой приложение и скопируй команду заново.',
        disconnected: '✅ Агент отключён. AI ассистент выключен.',
        notConnected: 'Агент не подключён.',
        statusConnected: (connectedAt: string, lastPing: string) =>
          `🟢 Агент подключён\n\nПодключён: ${connectedAt}\nПоследний пинг: ${lastPing}`,
        statusDisconnected:
          '🔴 Агент не запущен.\n\nЗапусти приложение HyperBotAgent на Mac. Если не установлен — /connect.',
        statusDisabledByUser:
          '⚠️ Приложение агента подключено, но инструменты AI ассистента отключены.\n\nИспользуй /activate <код> для повторного включения.',
      },
    },
    callbackErrors: {
      notFound: 'Не найдено',
      error: 'Ошибка',
      notAuthorized: 'Нет доступа',
      notConfigured: 'Не настроено',
      couldNotSendImage: '⚠️ Не удалось отправить изображение',
      renderFailed: '⚠️ Ошибка генерации',
      imageGenerationFailed: '⚠️ Не удалось сгенерировать изображение. Смотри текстовую версию выше.',
      proposalNotFound: 'Предложение не найдено',
      threadNotFound: 'Тред не найден',
      threadClosed: 'Тред закрыт',
      sendReplyMessage: 'Напиши ответное сообщение',
      intentApproved: '✅ Интент одобрен',
      intentRejected: '❌ Интент отклонён',
      sendEditInstructions: 'Напиши инструкции для редактирования...',
      notYourQuestion: 'Не твой вопрос',
      unavailable: 'Недоступно',
      closed: '❌ Закрыто',
      editCancelled: '❌ Редактирование отменено',
      deletionCancelled: '❌ Удаление отменено',
      disconnectCancelled: '❌ Отключение отменено',
      cancelled: '❌ Отменено',
      invitationCancelled: '❌ Приглашение отменено',
      sentBelow: '✅ Отправлено ниже',
      forwardHint: '↗️ Перешлите это сообщение',
      sceneHelpPrompt: 'AI поможет. Просто напиши — что затрудняет?',
      invitePickContact: (title: string) => `📨 ${title}\nВыберите контакт:`,
      inviteSelectUser: '👤 Выбрать пользователя',
      inviteSelectGroup: '👥 Выбрать группу',
      inviteTapButton: 'Нажмите кнопку ниже:',
      inviteSending: '⏳ Отправляем приглашения...',
      proposalAccepted: (title: string) => `✅ Предложение принято. Событие «${title}» обновлено.`,
      proposalAcceptedNoEvent: '✅ Предложение принято.',
      proposalRejected: '❌ Предложение отклонено.',
      proposalAcceptedNotification: '✅ Твоё предложение по редактированию принято.',
      proposalRejectedNotification: '❌ Твоё предложение по редактированию отклонено.',
      feedbackThreadResolved: 'Твой вопрос помечен как решённый.',
      adminReplySent: 'Ответ отправлен.',
      adminReplyDeliveredToGroup: 'Доставлено в группу (пользователь не начал чат с ботом).',
      adminReplyFailed: '⚠️ Не удалось доставить — пользователь не начал чат с ботом.',
      proposalAlreadyProcessed: (status: string) => {
        const map: Record<string, string> = { pending: 'в ожидании', accepted: 'принято', rejected: 'отклонено' };
        return `Уже ${map[status] ?? status}`;
      },
    },
    notifications: {
      morning: 'Доброе утро! Ваш день:',
      morningFree: 'Доброе утро!',
      evening: 'Расписание на завтра:',
      eveningFree: 'Добрый вечер!',
      reminder: 'Напоминание:',
      reminders: 'Напоминания',
      inLabel: 'через',
      startingNow: 'начинается!',
      eventsCount: (n: number) => `${n} ${ruPlural(n, 'событие', 'события', 'событий')}`,
      goodNight: 'Спокойной ночи!',
      tomorrow: 'завтра',
      haveADay: 'Продуктивного дня!',
      eveHoliday: (name: string) => `🎉 Завтра праздник: ${name}`,
      weeklyDigest: (range: string) => `📅 Неделя ${range}:`,
      noEvents: 'нет событий',
      allDay: 'Весь день',
      freeDayMorning:
        'Сегодня нет событий — день свободен!\nХочешь что-то запланировать? Просто напиши сообщение, или используй /add.',
      freeDayEvening:
        'Завтра нет событий — день свободен!\nХочешь запланировать что-то заранее? Просто напиши сообщение, или используй /add.',
      durationHours: (h: number) => `${h} ${ruPlural(h, 'час', 'часа', 'часов')}`,
      durationMinutes: (m: number) => `${m} ${ruPlural(m, 'минуту', 'минуты', 'минут')}`,
      clockChangeForward: (duration: string) =>
        `🕐 Сегодня ночью часы перевели на ${duration} вперёд. Проверь, что будильник и встречи правильно настроены!`,
      clockChangeBack: (duration: string) =>
        `🕐 Сегодня ночью часы перевели на ${duration} назад. Проверь, что будильник и встречи правильно настроены!`,
    },
    weather: {
      tempCurrent: (current: number, min: number, max: number) => `${current}°C (${min}..${max}°C)`,
      tempRange: (min: number, max: number) => `${min}..${max}°C`,
      wind: (ms: number) => `${ms} м/с`,
      weekForecast: '🌤 Погода на неделю:',
    },
    botTips: {
      // ── Создание событий ──
      voice_create: '💡 Отправь голосовое сообщение — я пойму и создам событие!',
      add_command: '💡 Используй /add чтобы создать событие по шагам.',
      natural_language: '💡 Просто напиши: «Стоматолог в пятницу в 15:00» — я всё пойму.',
      recurring_events: '💡 Умею создавать повторяющиеся события — попробуй «стендап каждый будний день в 10:00».',
      complex_recurrence: '💡 «Обед с Аней каждый второй четверг в 13:00» — сложные повторения тоже работают.',
      ics_import: '💡 Импортируй календарь — просто отправь .ics файл в этот чат.',
      // ── Напоминания и не забыть ──
      call_before_flight:
        '💡 Чтобы не опоздать на самолёт — добавь время прибытия в аэропорт и попроси меня позвонить!',
      multiple_reminders: '💡 Несколько напоминаний: «напомни за 1 день и за 2 часа до встречи».',
      voice_calls: '💡 Я могу позвонить тебе перед важным событием — включи звонки в /settings.',
      daily_medicine: '💡 «Напоминай пить таблетки каждый день в 8 утра» — и я буду присылать уведомление.',
      birthday_reminder: '💡 Поставь напоминание о дне рождения друга заранее — успеешь выбрать подарок.',
      // ── Планирование и обзор ──
      week_overview: '💡 Спроси «что у меня на этой неделе?» — получишь быстрый обзор.',
      free_slots: '💡 «Когда я свободен в среду?» — найду свободные окна в расписании.',
      month_view: '💡 Используй /month чтобы увидеть календарь на весь месяц.',
      meeting_count: '💡 «Сколько у меня встреч на этой неделе?» — посчитаю и подведу итог.',
      morning_agenda:
        '💡 Настрой утреннюю сводку, чтобы каждый день начинать с плана — «настрой утреннюю сводку на 7:30».',
      evening_review:
        '💡 Включи вечерний обзор, чтобы подготовиться к завтрашнему дню — «включи вечерний обзор в 21:00».',
      // ── Шаринг и совместная работа ──
      share_schedule: '💡 Поделись расписанием: «покажи мою неделю @username» — увидит твои события.',
      invite_people: '💡 Приглашай людей: «пригласи @anna на ужин в пятницу».',
      accept_decline: '💡 Получил приглашение? Можешь принять, отклонить или предложить другое время.',
      group_calendar: '💡 Добавь бота в групповой чат — и ведите общий календарь!',
      secretary_access: '💡 Дай коллеге доступ секретаря, чтобы он управлял твоим календарём, когда ты занят.',
      // ── Google Calendar ──
      connect_google: '💡 Подключи Google Calendar через /connect_google — все события синхронизируются автоматически.',
      google_sync: '💡 После подключения Google все твои календари появятся здесь.',
      // ── Жизненные ситуации: Путешествия ──
      pack_suitcase:
        '💡 Собираешься в поездку? Добавь «Собрать чемодан» за день и «Такси в аэропорт» с точным временем.',
      hotel_checkin: '💡 Добавь время заезда и выезда из отеля — не пропустишь дедлайн.',
      visa_appointment:
        '💡 «Запись на визу 15 марта в 9:00, напомни за неделю и за день» — чтобы подготовить документы.',
      timezone_change: '💡 Меняешь часовой пояс? Скажи «поменяй мой часовой пояс на America/New_York».',
      // ── Жизненные ситуации: Здоровье ──
      doctor_checkup: '💡 «Визит к врачу каждые 6 месяцев» — не забудешь о плановых обследованиях.',
      gym_sessions: '💡 Тренировки: «зал каждый пн, ср, пт в 19:00» — следи за регулярностью.',
      drink_water: '💡 «Напоминай пить воду каждые 2 часа» — здоровые привычки в календаре!',
      // ── Жизненные ситуации: Работа ──
      weekly_oneone: '💡 Еженедельный 1-on-1? «1-on-1 с руководителем каждый вторник в 16:00, напомни за 15 мин».',
      sprint_review: '💡 «Ретро каждую вторую пятницу в 15:00» — двухнедельные повторения тоже умею.',
      prep_time: '💡 Перед презентацией добавь время на подготовку: «Подготовить слайды — пт с 14:00 до 16:00».',
      event_descriptions: '💡 Используй описания событий, чтобы хранить повестки и заметки к встречам.',
      // ── Жизненные ситуации: Личное ──
      anniversary: '💡 Никогда не забывай годовщину — «Годовщина свадьбы каждый год 15 июня».',
      movie_premieres: '💡 Добавляй премьеры фильмов, концерты или релизы игр, которых ждёшь.',
      rent_payment: '💡 «Оплата аренды каждый месяц 1 числа» — финансовые дедлайны под контролем.',
      subscriptions: '💡 Подписки: «Продление Netflix каждый месяц 12 числа» — знай, когда списание.',
      reading_challenge: '💡 «Читать 30 минут каждый вечер в 21:00» — формируй полезные привычки.',
      // ── Жизненные ситуации: Семья ──
      family_calendar: '💡 Веди семейный календарь в общем чате — все видят школьные события и кружки.',
      kids_swimming: '💡 «Бассейн у детей каждую субботу в 10:00» — семейные рутины легко.',
      school_events: '💡 Добавляй родительские собрания, утренники и каникулы в групповой календарь.',
      // ── Жизненные ситуации: Социальное ──
      birthday_party: '💡 «День рождения Макса — суббота в 18:00, Паб» — а потом пригласи друзей из контактов.',
      decline_propose:
        '💡 Не можешь прийти? Отклони приглашение и предложи удобное время — организатор получит уведомление.',
      find_free_time: '💡 Ищешь время для встречи? «Когда я свободен в субботу днём?»',
      // ── Мощные фичи ──
      context_awareness: '💡 Я помню контекст — скажи «перенеси на 15:00» и я пойму, какое событие.',
      automated_reminders: '💡 Запланируй автоматические сообщения: «напоминай каждую пятницу в 17:00 сдать таймшиты».',
      public_holidays: '💡 Через /holidays подпишись на праздники — они появятся в календаре.',
      save_contacts: '💡 Сохраняй контакты и приглашай по имени — не нужно помнить юзернеймы.',
      quiet_hours: '💡 Настрой тихие часы, чтобы я не беспокоил ночью — смотри /settings.',
      language_switch: '💡 Я говорю по-русски и по-английски — сменить язык можно в /settings.',
      action_log: '💡 Отправь /log чтобы увидеть полную историю действий с календарём.',
      past_events: '💡 «Что у меня было в прошлый вторник?» — я могу посмотреть прошлые события.',
    },
    gtdQuotes: [
      // Дэвид Аллен, «Как привести дела в порядок» (Getting Things Done, 2001/2015)
      // Цитаты в переводе, верифицированы по множеству открытых источников
      '📖 «Твой разум создан для того, чтобы рождать идеи, а не хранить их.» — Дэвид Аллен, GTD, гл. 1',
      '📖 «Если ты не уделяешь должного внимания тому, что занимает твоё внимание, оно потребует больше внимания, чем заслуживает.» — Дэвид Аллен, GTD, гл. 2',
      '📖 «Твоя способность генерировать энергию прямо пропорциональна твоей способности расслабляться.» — Дэвид Аллен, GTD, гл. 1',
      '📖 «Ты не можешь «сделать» проект — ты можешь лишь выполнять конкретные шаги, связанные с ним.» — Дэвид Аллен, GTD, гл. 3',
      '📖 «Большая часть стресса, который люди испытывают, возникает не от избытка дел. Он возникает от того, что они не доводят до конца начатое.» — Дэвид Аллен, GTD, гл. 6',
      '📖 «Легче через действие прийти к правильному настрою, чем через настрой прийти к действию.» — Дэвид Аллен, GTD, гл. 12',
      '📖 «Большинство людей лучше всего чувствуют себя на работе за неделю до отпуска. Но дело не в отпуске. Что ты делаешь в последнюю неделю перед поездкой? Разгребаешь дела, закрываешь задачи, пересматриваешь обязательства. Я предлагаю делать это еженедельно, а не раз в год.» — Дэвид Аллен, GTD, гл. 8',
      '📖 «Обычно существует обратная зависимость: чем больше что-то занимает твои мысли, тем меньше это делается.» — Дэвид Аллен, GTD, гл. 1',
      '📖 «Ты можешь спокойно относиться к тому, что не делаешь, только когда точно знаешь, что именно ты не делаешь.» — Дэвид Аллен, GTD, гл. 9',
      '📖 «Всё, что находится не там, где должно быть, и не в том состоянии — это «открытая петля», которая будет перетягивать твоё внимание.» — Дэвид Аллен, GTD, гл. 2',
      '📖 «Чтобы довести дело до конца, нужны два компонента: определить (1) что значит «сделано» (результат) и (2) как выглядит «делание» (действие).» — Дэвид Аллен, GTD, гл. 2',
      '📖 «Твоя голова — для того, чтобы рождать идеи, а не для хранения. Для хранения нужна надёжная система.» — Дэвид Аллен, GTD, гл. 4',
      '📖 «Правило двух минут: если следующее действие можно сделать за две минуты или меньше, делай его сразу.» — Дэвид Аллен, GTD, гл. 6',
      '📖 «Думай как человек действия, действуй как человек мысли.» — Анри Бергсон, цит. в GTD, гл. 3',
      '📖 «Главный секрет продуктивного мышления и действий — направлять внимание на нужные вещи в нужное время.» — Дэвид Аллен, GTD, гл. 9',
      '📖 «Один из лучших приёмов повышения продуктивности — иметь организованные, готовые к обзору напоминания о действиях.» — Дэвид Аллен, GTD, гл. 7',
      '📖 «Еженедельный обзор — это время собрать и обработать все «входящие», обновить списки и привести систему в чистое, ясное, актуальное состояние.» — Дэвид Аллен, GTD, гл. 8',
      '📖 «Отличный молоток не сделает из тебя отличного плотника, но отличный плотник всегда захочет иметь отличный молоток.» — Дэвид Аллен, GTD, гл. 5',
    ],
    atomicHabitsQuotes: [
      // Джеймс Клир, «Атомные привычки» (2018)
      '📖 «Ты не поднимаешься до уровня своих целей. Ты падаешь до уровня своих систем.» — Джеймс Клир, Атомные привычки, гл. 1',
      '📖 «Каждое твоё действие — это голос за тот тип человека, которым ты хочешь стать.» — Джеймс Клир, Атомные привычки, гл. 2',
      '📖 «Привычки — это сложный процент самосовершенствования.» — Джеймс Клир, Атомные привычки, гл. 1',
      '📖 «Самый эффективный способ изменить привычки — сосредоточиться не на том, чего ты хочешь достичь, а на том, кем ты хочешь стать.» — Джеймс Клир, Атомные привычки, гл. 2',
      '📖 «Будь дизайнером своего мира, а не просто его потребителем.» — Джеймс Клир, Атомные привычки, гл. 6',
      '📖 «Когда ты влюбляешься в процесс, а не в результат, тебе не нужно ждать разрешения быть счастливым.» — Джеймс Клир, Атомные привычки, гл. 1',
      '📖 «Избавиться от плохой привычки — как выкорчевать мощный дуб внутри себя.» — Джеймс Клир, Атомные привычки, гл. 7',
      '📖 «Успех — это продукт ежедневных привычек, а не единичных трансформаций.» — Джеймс Клир, Атомные привычки, гл. 1',
      '📖 «Время усиливает разрыв между успехом и провалом. Оно умножает то, чем ты его кормишь.» — Джеймс Клир, Атомные привычки, гл. 1',
      '📖 «Тебя должна волновать текущая траектория, а не текущие результаты.» — Джеймс Клир, Атомные привычки, гл. 1',
      '📖 «Цель постановки целей — выиграть игру. Цель построения систем — продолжать играть.» — Джеймс Клир, Атомные привычки, гл. 1',
      '📖 «Пропустить один раз — случайность. Пропустить дважды — начало новой привычки.» — Джеймс Клир, Атомные привычки, гл. 16',
    ],
    deepWorkQuotes: [
      // Кэл Ньюпорт, «Глубокая работа» (2016)
      '📖 «Если ты не производишь результат — ты не преуспеешь, независимо от таланта и навыков.» — Кэл Ньюпорт, Глубокая работа, гл. 1',
      '📖 «Ясность в том, что важно, даёт ясность в том, что не важно.» — Кэл Ньюпорт, Глубокая работа, гл. 4',
      '📖 «Способность к глубокой работе становится всё более редкой именно тогда, когда становится всё более ценной.» — Кэл Ньюпорт, Глубокая работа, введение',
      '📖 «Два ключевых навыка для успеха в новой экономике: быстро осваивать сложные вещи и производить результат на элитном уровне.» — Кэл Ньюпорт, Глубокая работа, гл. 1',
      '📖 «Кто ты, что ты думаешь, чувствуешь и делаешь, что любишь — это сумма того, на чём ты фокусируешься.» — Кэл Ньюпорт, Глубокая работа, гл. 3',
      '📖 «Глубокая жизнь — это хорошая жизнь, как ни посмотри.» — Кэл Ньюпорт, Глубокая работа, заключение',
      '📖 «Попытки углубить фокус обречены, если ты одновременно не отучишь свой мозг от зависимости к отвлечениям.» — Кэл Ньюпорт, Глубокая работа, правило 2',
      '📖 «Ключ к глубокой работе — выйти за рамки добрых намерений и добавить рутины и ритуалы в рабочую жизнь.» — Кэл Ньюпорт, Глубокая работа, правило 1',
      '📖 «Относись к своему времени с уважением. Планируй каждую минуту дня.» — Кэл Ньюпорт, Глубокая работа, правило 4',
      '📖 «Не бери перерывы от отвлечений. Бери перерывы от фокуса.» — Кэл Ньюпорт, Глубокая работа, правило 2',
    ],
    sevenHabitsQuotes: [
      // Стивен Кови, «7 навыков высокоэффективных людей» (1989)
      '📖 «Главное — не расставлять приоритеты в расписании, а планировать приоритеты.» — Стивен Кови, 7 навыков, навык 3',
      '📖 «Начинай, представляя конечную цель.» — Стивен Кови, 7 навыков, навык 2',
      '📖 «Сначала делай то, что нужно делать сначала.» — Стивен Кови, 7 навыков, навык 3',
      '📖 «Большинство из нас тратит слишком много времени на срочное и слишком мало на важное.» — Стивен Кови, 7 навыков, навык 3',
      '📖 «Главное — сохранять главное главным.» — Стивен Кови, 7 навыков, навык 3',
      '📖 «Посей мысль — пожнёшь действие; посей действие — пожнёшь привычку; посей привычку — пожнёшь характер; посей характер — пожнёшь судьбу.» — Стивен Кови, 7 навыков, навык 1',
      '📖 «Между стимулом и реакцией есть пространство. В этом пространстве — наша свобода и сила выбирать свой ответ.» — Стивен Кови, 7 навыков, навык 1',
      '📖 «Будь проактивным. Эффективные люди не просто реагируют на обстоятельства — они их создают.» — Стивен Кови, 7 навыков, навык 1',
      '📖 «Сначала стремись понять, потом — быть понятым.» — Стивен Кови, 7 навыков, навык 5',
      '📖 «Живи воображением, а не историей.» — Стивен Кови, 7 навыков, навык 2',
    ],
    contextualTips: {
      noEveningReview:
        '💡 Утро настроено — а вечер? Включи вечерний обзор, чтобы готовиться к завтрашнему дню: «включи вечерний обзор в 21:00».',
      noMorningAgenda:
        '💡 Хочешь начинать каждый день с плана? Включи утреннюю сводку: «настрой утреннюю сводку на 7:30».',
      noQuietHours: '💡 Защити свой сон — настрой тихие часы, чтобы я не беспокоил ночью. Смотри /settings.',
      noGoogleCalendar: '💡 Подключи Google Calendar, чтобы видеть все события в одном месте — /connect_google.',
      noCountry: '💡 Укажи свою страну, чтобы праздники появились в календаре — /holidays.',
      noVoiceCalls:
        '💡 Я могу звонить перед важными событиями, чтобы ты ничего не пропустил. Включи звонки в /settings.',
    },
    speech: {
      allDay: 'весь день',
      noEvents: 'нет событий',
      at: 'в',
      morningIntro: (dateLabel: string) => `Доброе утро. Сегодня, ${dateLabel}.`,
      morningOutro: 'Продуктивного дня!',
      eveningIntro: (dateLabel: string) => `Добрый вечер. Завтра, ${dateLabel}.`,
      eveningOutro: 'Спокойной ночи!',
      weeklyDigestIntro: (weekRange: string) => `Еженедельный дайджест на неделю ${weekRange}.`,
      reminderIntro: (cleanTitle: string, timeStr: string) => `Календарное напоминание. ${cleanTitle} в ${timeStr}.`,
      location: (loc: string) => `Место: ${loc}.`,
      batchIntro: (count: number) =>
        `Календарное напоминание. ${count} ${ruPlural(count, 'событие', 'события', 'событий')} начинаются скоро:`,
      eventAt: (title: string, timeStr: string) => `${title} в ${timeStr}.`,
    },
  },
} as const;

export type Lang = keyof typeof MSG;
export type Messages = (typeof MSG)[Lang];

/** Validate a string to Lang, defaulting to 'en' for unknown values. */
export function toLang(value: string | null | undefined): Lang {
  if (value === 'ru' || value === 'en') return value;
  return 'en';
}

export function t(lang: Lang): Messages {
  return MSG[lang] || MSG.en;
}
