// src/config/constants.ts

// Rate limits
export const RATE_LIMIT = {
  MESSAGES_PER_MINUTE: 30,
  MESSAGES_PER_HOUR: 200,
  ADD_PER_HOUR: 20,
  EXPORT_PER_HOUR: 5,
  COOLDOWN_MS: 60_000,
  AI_PER_MINUTE: 10,
  AI_PER_HOUR: 60,
} as const;

// Defaults
export const DEFAULTS = {
  LANGUAGE: 'en' as const,
  TIMEZONE: 'UTC',
  REMINDER_MINUTES: 15,
  WEEK_STARTS_ON: 1 as const, // Monday
} as const;

// Callback data prefixes
export const CB = {
  EVENT_VIEW: 'ev',
  EVENT_EDIT: 'ee',
  EVENT_DELETE: 'ed',
  EVENT_DELETE_CONFIRM: 'edc',
  EVENT_RECURRENCE: 'er',
  EVENT_REMINDER: 'erm',
  ONBOARD_LANG: 'ol',
  ONBOARD_TZ_REGION: 'otr',
  ONBOARD_TZ: 'ot',
  ONBOARD_COUNTRY: 'oc',
  ONBOARD_AGENDA: 'oa',
  MONTH_NAV: 'mn',
  SETTINGS: 'st',
  EDIT_FIELD: 'ef',
  ADD_STEP: 'as',
  RECURRENCE_DELETE: 'erd',
  ADD_RECURRENCE: 'ar',
  ADD_REC_END: 'are',
  ADD_SKIP: 'ask',
  HOLIDAYS: 'hl',
  NOTIFY: 'nf',
  GCAL: 'gc',
  INVITATION_ACTION: 'inv',
  SHARE_CONFIRM: 'share_cf',
  SHARE_EVENT: 'share_evt',
} as const;

// i18n messages
export const MSG = {
  en: {
    welcome: '🌍 Choose your language / Выберите язык:',
    tz_prompt: "Now let's set your timezone. The most accurate way is to share your location.",
    tz_detected: (tz: string, offset: string) => `Got it! Your timezone is ${tz} (${offset}).\nIs this correct?`,
    tz_confirm_yes: 'Yes ✓',
    tz_confirm_no: 'No, choose manually',
    share_location: '📍 Share Location',
    choose_manually: '⌨️ Choose Manually',
    country_prompt: 'Want to see public holidays in your calendar?',
    country_skip: 'Skip',
    agenda_prompt: "I can send you a morning summary of your day's events.\n\nChoose a time for the daily agenda:",
    onboard_done:
      "✅ All set! Here's what you can do:\n\n/add — create your first event\n/today — view today's schedule\n/help — see all commands",
    no_events_today: (date: string) => `📅 ${date}\n\nNo events today. Use /add to create one.`,
    no_events: 'No events in this range.',
    event_created: (title: string) => `✅ Created: "${title}"`,
    event_deleted: (title: string) => `🗑 Deleted: "${title}"`,
    event_updated: (title: string) => `✏️ Updated: "${title}"`,
    confirm_delete: (title: string) => `Delete "${title}"?`,
    search_no_results: 'No events found.',
    something_wrong: 'Something went wrong. Try again or use /help.',
    rate_limited: 'Slow down, too many messages.',
    add_title_prompt: "Let's create an event. What's the title?",
    add_time_prompt: 'When? (e.g., "tomorrow 18:00", "Mar 15 19:30")',
    add_duration_prompt: 'How long? (e.g., "1h", "30m", "2h30m") or skip for no end time.',
    add_description_prompt: 'Description? (send text or "skip")',
    add_location_prompt: 'Location? (send text or "skip")',
    edit_pick: 'Which event to edit? Pick from upcoming:',
    delete_pick: 'Which event to delete?',
    free_header: (date: string) => `📋 Free slots ${date}:`,
    pong: (ms: number) => `pong (${ms}ms)`,
    welcome_back: 'Welcome back! Use /help for commands.',
    recurrence_prompt: 'Repeat this event?',
    recurrence_end_prompt: 'When should it stop repeating?',
    recurrence_custom_prompt: 'Describe the recurrence (e.g., "every 2 weeks", "daily"):',
    recurrence_until_prompt: 'Send the end date (e.g., "Mar 30", "15 января"):',
    recurrence_count_prompt: 'How many times?',
    skip: 'Skip',
    holidays_menu: '🌍 <b>Holiday Subscriptions</b>',
    holidays_no_subs: 'No countries added yet. Tap "+ Add" to subscribe.',
    holidays_added: (country: string) => `✅ Subscribed to ${country}`,
    holidays_removed: (country: string) => `Removed ${country}`,
    holidays_set_primary: (country: string) => `${country} set as primary`,
    holidays_pick_region: 'Choose a region:',
    holidays_pick_country: 'Choose a country:',
    holidays_upcoming: '📅 <b>Upcoming Holidays</b>',
    holidays_none_upcoming: 'No upcoming holidays for your subscriptions.',
    holidays_day_off: '🎉 Day off!',
    holidays_manage_prompt: 'Choose a subscription to manage:',
    holidays_notify_on: (country: string) => `${country}: notifications ON`,
    holidays_notify_off: (country: string) => `${country}: notifications OFF`,
    ai_error: 'AI is temporarily unavailable. Use bot commands (/help).',
    ai_clear_history: 'Chat history cleared.',
    notify_menu: '⚙️ Notification Settings',
    notify_morning: '🌅 Morning Agenda',
    notify_morning_status: (enabled: boolean, time: string) => `Morning agenda: ${enabled ? `✅ ${time}` : '❌'}`,
    notify_evening: '🌙 Evening Review',
    notify_evening_status: (enabled: boolean, time: string) => `Evening review: ${enabled ? `✅ ${time}` : '❌'}`,
    notify_reminders: '⏰ Default Reminders',
    notify_quiet: '🔇 Quiet Hours',
    notify_quiet_status: (enabled: boolean, start: string, end: string) =>
      `Quiet hours: ${enabled ? `✅ ${start} — ${end}` : '❌'}`,
    notify_pick_hour: 'Pick hour:',
    notify_pick_minute: 'Pick minute:',
    notify_updated: 'Settings updated',
    notify_intervals_label: (intervals: number[]) =>
      `Default reminders: ${intervals.map((m) => (m >= 60 ? `${m / 60}hr` : `${m}min`)).join(', ')}`,
    gcal_onboarding:
      'Want to sync with Google Calendar?\n\nYour events will stay in the bot either way. Google Calendar sync is optional but gives you:\n- See bot events in your phone calendar\n- Changes in Google Calendar auto-sync to the bot\n- Two-way sync keeps everything up to date',
    gcal_onboarding_maybe_later: 'Maybe Later',
    gcal_not_configured: 'Google Calendar sync is not configured. Contact the admin.',
    gcal_already_connected: 'Google Calendar is already connected. Use /disconnect_google first to reconnect.',
    gcal_connect_prompt: '🔗 Connect Google Calendar to sync your events bidirectionally.',
    gcal_connect_button: 'Connect Google Calendar',
    gcal_connected: '✅ Google Calendar connected! Now pick which calendars to sync.',
    gcal_disconnected: '✅ Google Calendar disconnected. Your local events are untouched.',
    gcal_disconnect_confirm: 'Disconnect Google Calendar? Your events will stay in the bot.',
    gcal_disconnect_yes: 'Yes, disconnect',
    gcal_disconnect_no: 'Cancel',
    gcal_calendar_picker: 'Select calendars to sync (tap to toggle):',
    gcal_calendar_done: 'Done ✓',
    gcal_calendar_readonly: '(read-only)',
    gcal_calendars_saved: '✅ Calendar selection saved. Initial sync starting...',
    gcal_sync_complete: '✅ Initial sync complete. Your Google events are now in the bot.',
    gcal_revoked: '⚠️ Google Calendar connection lost. Use /connect_google to reconnect.',
    gcal_conflict: (title: string, winner: string) =>
      `⚠️ Sync conflict on "${title}"\n\n${winner === 'google' ? 'Google Calendar' : 'Local'} version was applied (more recent).`,
    invite_usage: 'Usage: /invite <user_id> <event_id>',
    invite_delivered: (title: string) => `📨 Invitation to "<b>${title}</b>" sent`,
    invite_deep_link: (title: string, url: string) =>
      `The user hasn't started the bot yet. Forward this link so they can accept:\n\n${url}\n\n(Invitation to "<b>${title}</b>")`,
    invitation_sent: 'Invitation sent',
    invitation_received: (title: string, from: string) =>
      `📨 <b>Invitation</b>\n${from} invites you to: <b>${title}</b>`,
    invitation_accepted: 'Invitation accepted ✅',
    invitation_declined: 'Invitation declined ❌',
    invitation_maybe: 'Marked as maybe 🤔',
    invitation_cancelled: 'Invitation cancelled',
    invitation_expired: 'This invitation has expired',
    invitation_not_found: 'Invitation not found',
    invitation_already_sent: 'Invitation already sent to this user',
    invitations_disabled: 'This user has disabled invitations',
    privacy_current: (level: string) => `🔒 Current visibility: <b>${level}</b>`,
    share_preview: '📤 Preview — this is what will be shared:',
    share_sent: '✅ Shared successfully',
    share_cancelled: '❌ Share cancelled',
    no_events_to_share: 'No events to share for this period',
  },
  ru: {
    welcome: '🌍 Choose your language / Выберите язык:',
    tz_prompt: 'Установим часовой пояс. Самый точный способ — поделиться геолокацией.',
    tz_detected: (tz: string, offset: string) => `Ваш часовой пояс: ${tz} (${offset}).\nВсё верно?`,
    tz_confirm_yes: 'Да ✓',
    tz_confirm_no: 'Нет, выбрать вручную',
    share_location: '📍 Отправить геолокацию',
    choose_manually: '⌨️ Выбрать вручную',
    country_prompt: 'Показывать государственные праздники в календаре?',
    country_skip: 'Пропустить',
    agenda_prompt: 'Могу отправлять утреннюю сводку событий на день.\n\nВыберите время для утренней сводки:',
    onboard_done:
      '✅ Всё готово! Вот что можно сделать:\n\n/add — создать событие\n/today — расписание на сегодня\n/help — список команд',
    no_events_today: (date: string) => `📅 ${date}\n\nНет событий. Используйте /add для создания.`,
    no_events: 'Нет событий за этот период.',
    event_created: (title: string) => `✅ Создано: "${title}"`,
    event_deleted: (title: string) => `🗑 Удалено: "${title}"`,
    event_updated: (title: string) => `✏️ Обновлено: "${title}"`,
    confirm_delete: (title: string) => `Удалить "${title}"?`,
    search_no_results: 'Ничего не найдено.',
    something_wrong: 'Что-то пошло не так. Попробуйте ещё раз или /help.',
    rate_limited: 'Слишком много сообщений, подождите.',
    add_title_prompt: 'Создаём событие. Как назовём?',
    add_time_prompt: 'Когда? (например, "завтра 18:00", "15 мар 19:30")',
    add_duration_prompt: 'Сколько длится? (например, "1ч", "30м") или пропустите.',
    add_description_prompt: 'Описание? (текст или "пропустить")',
    add_location_prompt: 'Место? (текст или "пропустить")',
    edit_pick: 'Какое событие редактировать?',
    delete_pick: 'Какое событие удалить?',
    free_header: (date: string) => `📋 Свободные слоты ${date}:`,
    pong: (ms: number) => `понг (${ms}мс)`,
    welcome_back: 'С возвращением! /help для списка команд.',
    recurrence_prompt: 'Повторять событие?',
    recurrence_end_prompt: 'Когда прекратить повторение?',
    recurrence_custom_prompt: 'Опишите повторение (напр. "каждые 2 недели", "ежедневно"):',
    recurrence_until_prompt: 'Отправьте дату окончания (напр. "30 мар", "15 января"):',
    recurrence_count_prompt: 'Сколько раз?',
    skip: 'Пропустить',
    holidays_menu: '🌍 <b>Праздники</b>',
    holidays_no_subs: 'Нет подписок. Нажмите "+ Добавить" чтобы подписаться.',
    holidays_added: (country: string) => `✅ Подписка на ${country}`,
    holidays_removed: (country: string) => `Удалено: ${country}`,
    holidays_set_primary: (country: string) => `${country} — основная страна`,
    holidays_pick_region: 'Выберите регион:',
    holidays_pick_country: 'Выберите страну:',
    holidays_upcoming: '📅 <b>Ближайшие праздники</b>',
    holidays_none_upcoming: 'Нет ближайших праздников по вашим подпискам.',
    holidays_day_off: '🎉 Выходной!',
    holidays_manage_prompt: 'Выберите подписку для управления:',
    holidays_notify_on: (country: string) => `${country}: уведомления ВКЛ`,
    holidays_notify_off: (country: string) => `${country}: уведомления ВЫКЛ`,
    ai_error: 'ИИ временно недоступен. Используйте команды бота (/help).',
    ai_clear_history: 'История чата очищена.',
    notify_menu: '⚙️ Настройки уведомлений',
    notify_morning: '🌅 Утренняя повестка',
    notify_morning_status: (enabled: boolean, time: string) => `Утренняя повестка: ${enabled ? `✅ ${time}` : '❌'}`,
    notify_evening: '🌙 Вечерний обзор',
    notify_evening_status: (enabled: boolean, time: string) => `Вечерний обзор: ${enabled ? `✅ ${time}` : '❌'}`,
    notify_reminders: '⏰ Напоминания по умолчанию',
    notify_quiet: '🔇 Тихие часы',
    notify_quiet_status: (enabled: boolean, start: string, end: string) =>
      `Тихие часы: ${enabled ? `✅ ${start} — ${end}` : '❌'}`,
    notify_pick_hour: 'Выберите час:',
    notify_pick_minute: 'Выберите минуту:',
    notify_updated: 'Настройки обновлены',
    notify_intervals_label: (intervals: number[]) =>
      `Напоминания: ${intervals.map((m) => (m >= 60 ? `${m / 60}ч` : `${m}мин`)).join(', ')}`,
    gcal_onboarding:
      'Хотите синхронизировать с Google Calendar?\n\nСобытия останутся в боте в любом случае. Синхронизация даёт:\n- Просмотр событий бота в Google Calendar\n- Изменения в Google Calendar авто-синхронизируются\n- Двусторонняя синхронизация',
    gcal_onboarding_maybe_later: 'Позже',
    gcal_not_configured: 'Синхронизация с Google Calendar не настроена. Обратитесь к администратору.',
    gcal_already_connected: 'Google Calendar уже подключён. Используйте /disconnect_google чтобы переподключить.',
    gcal_connect_prompt: '🔗 Подключите Google Calendar для двусторонней синхронизации событий.',
    gcal_connect_button: 'Подключить Google Calendar',
    gcal_connected: '✅ Google Calendar подключён! Выберите календари для синхронизации.',
    gcal_disconnected: '✅ Google Calendar отключён. Локальные события сохранены.',
    gcal_disconnect_confirm: 'Отключить Google Calendar? События останутся в боте.',
    gcal_disconnect_yes: 'Да, отключить',
    gcal_disconnect_no: 'Отмена',
    gcal_calendar_picker: 'Выберите календари для синхронизации (нажмите для переключения):',
    gcal_calendar_done: 'Готово ✓',
    gcal_calendar_readonly: '(только чтение)',
    gcal_calendars_saved: '✅ Выбор сохранён. Начинается синхронизация...',
    gcal_sync_complete: '✅ Синхронизация завершена. Ваши события из Google теперь в боте.',
    gcal_revoked: '⚠️ Связь с Google Calendar потеряна. Используйте /connect_google чтобы переподключить.',
    gcal_conflict: (title: string, winner: string) =>
      `⚠️ Конфликт синхронизации "${title}"\n\n${winner === 'google' ? 'Google Calendar' : 'Локальная'} версия применена (более новая).`,
    invite_usage: 'Использование: /invite <user_id> <event_id>',
    invite_delivered: (title: string) => `📨 Приглашение на "<b>${title}</b>" отправлено`,
    invite_deep_link: (title: string, url: string) =>
      `Пользователь ещё не запустил бота. Перешлите ссылку для принятия:\n\n${url}\n\n(Приглашение на "<b>${title}</b>")`,
    invitation_sent: 'Приглашение отправлено',
    invitation_received: (title: string, from: string) =>
      `📨 <b>Приглашение</b>\n${from} приглашает вас: <b>${title}</b>`,
    invitation_accepted: 'Приглашение принято ✅',
    invitation_declined: 'Приглашение отклонено ❌',
    invitation_maybe: 'Отмечено как "возможно" 🤔',
    invitation_cancelled: 'Приглашение отменено',
    invitation_expired: 'Это приглашение истекло',
    invitation_not_found: 'Приглашение не найдено',
    invitation_already_sent: 'Приглашение уже отправлено этому пользователю',
    invitations_disabled: 'Этот пользователь отключил приглашения',
    privacy_current: (level: string) => `🔒 Текущая видимость: <b>${level}</b>`,
    share_preview: '📤 Превью — вот что будет отправлено:',
    share_sent: '✅ Отправлено',
    share_cancelled: '❌ Отправка отменена',
    no_events_to_share: 'Нет событий для этого периода',
  },
} as const;

export type Lang = keyof typeof MSG;
export type Messages = (typeof MSG)[Lang];

export function t(lang: Lang): Messages {
  return MSG[lang] || MSG.en;
}

// Popular timezone regions for manual selection
export const TZ_REGIONS: Record<string, string[]> = {
  Europe: [
    'Europe/London',
    'Europe/Paris',
    'Europe/Berlin',
    'Europe/Moscow',
    'Europe/Istanbul',
    'Europe/Kyiv',
    'Europe/Warsaw',
    'Europe/Rome',
    'Europe/Madrid',
    'Europe/Amsterdam',
    'Europe/Belgrade',
    'Europe/Helsinki',
  ],
  Asia: [
    'Asia/Dubai',
    'Asia/Kolkata',
    'Asia/Bangkok',
    'Asia/Singapore',
    'Asia/Tokyo',
    'Asia/Seoul',
    'Asia/Shanghai',
    'Asia/Hong_Kong',
    'Asia/Almaty',
    'Asia/Tbilisi',
    'Asia/Yerevan',
    'Asia/Tashkent',
  ],
  Americas: [
    'America/New_York',
    'America/Chicago',
    'America/Denver',
    'America/Los_Angeles',
    'America/Toronto',
    'America/Sao_Paulo',
    'America/Mexico_City',
    'America/Buenos_Aires',
  ],
  Africa: ['Africa/Cairo', 'Africa/Lagos', 'Africa/Johannesburg', 'Africa/Nairobi'],
  Oceania: ['Australia/Sydney', 'Australia/Melbourne', 'Pacific/Auckland'],
};
