// scripts/generate-fonts.ts
// Run once: bun run scripts/generate-fonts.ts

// Inter v20 — latin + cyrillic subsets
// URLs obtained from: https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap
const INTER_REGULAR_LATIN_URL = 'https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7.woff2';
const INTER_REGULAR_CYRILLIC_URL =
  'https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa0ZL7SUc.woff2';

async function downloadBase64(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  const buf = await res.arrayBuffer();
  return Buffer.from(buf).toString('base64');
}

const [regularLatin, regularCyrillic] = await Promise.all([
  downloadBase64(INTER_REGULAR_LATIN_URL),
  downloadBase64(INTER_REGULAR_CYRILLIC_URL),
]);

// Bold uses the same URLs as regular for latin/cyrillic in v20 variable font
// The weight is set via font-weight property
const boldLatin = regularLatin;
const boldCyrillic = regularCyrillic;

const output = `// Generated by scripts/generate-fonts.ts — do not edit manually

export const FONT_INTER_REGULAR_LATIN = "data:font/woff2;base64,${regularLatin}";

export const FONT_INTER_REGULAR_CYRILLIC = "data:font/woff2;base64,${regularCyrillic}";

export const FONT_INTER_BOLD_LATIN = "data:font/woff2;base64,${boldLatin}";

export const FONT_INTER_BOLD_CYRILLIC = "data:font/woff2;base64,${boldCyrillic}";

export const fontFaceCSS = \`
  @font-face {
    font-family: 'Inter';
    font-weight: 400;
    font-style: normal;
    unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
    src: url('\${FONT_INTER_REGULAR_CYRILLIC}') format('woff2');
  }
  @font-face {
    font-family: 'Inter';
    font-weight: 400;
    font-style: normal;
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
    src: url('\${FONT_INTER_REGULAR_LATIN}') format('woff2');
  }
  @font-face {
    font-family: 'Inter';
    font-weight: 700;
    font-style: normal;
    unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
    src: url('\${FONT_INTER_BOLD_CYRILLIC}') format('woff2');
  }
  @font-face {
    font-family: 'Inter';
    font-weight: 700;
    font-style: normal;
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
    src: url('\${FONT_INTER_BOLD_LATIN}') format('woff2');
  }
\`;
`;

await Bun.write('src/worker/templates/fonts.ts', output);
console.log('fonts.ts generated');
