// Intended jobs for recovered source candidates, not a claim of implemented behavior.
export const candidateTaskLabels: Record<string, string> = {
  list_contacts: 'Список личных контактов',
  find_contact_by_name: 'Найти контакт по имени',
  who_is_contact: 'Уточнить сведения о контакте',
  add_contact_to_book: 'Добавить человека в адресную книгу',
  rename_contact: 'Изменить имя контакта',
  delete_event_by_name: 'Удалить событие по названию',
  delete_next_event: 'Удалить ближайшее событие',
  clear_today_events: 'Очистить события сегодняшнего дня',
  cancel_event_by_time_today: 'Отменить событие сегодня по времени',
  cancel_event_by_time_tomorrow: 'Отменить событие завтра по времени',
  delete_last_created_event: 'Удалить последнее созданное событие',
  cancel_referenced_event: 'Отменить обсуждаемое событие',
  decline_event_invitation: 'Отклонить приглашение на событие',
  rename_event: 'Переименовать событие',
  change_event_location: 'Изменить место события',
  add_event_description: 'Добавить или заменить описание',
  add_participant_to_event: 'Пригласить участника в событие',
  remove_own_participation: 'Отказаться от собственного участия',
  extend_event_duration_minutes: 'Продлить событие на минуты',
  extend_event_duration_hours: 'Продлить событие на часы',
  shorten_event_duration_minutes: 'Сократить длительность события',
  get_upcoming_next: 'Показать ближайшее событие',
  show_specific_date: 'Расписание на указанную дату',
  show_day_after_tomorrow: 'Расписание послезавтра',
  show_this_month: 'Расписание текущего месяца',
  show_next_month: 'Расписание следующего месяца',
  show_weekend: 'Расписание на выходные',
  events_with_person: 'События с определённым человеком',
  count_events_today: 'Количество событий сегодня',
  count_events_week: 'Количество событий за неделю',
  count_events_month: 'Количество событий за месяц',
  free_slots_tomorrow: 'Свободное время завтра',
  free_slots_week: 'Свободное время на этой неделе',
  free_slots_next_week: 'Свободное время на следующей неделе',
  free_slots_on_date: 'Свободное время в указанную дату',
  am_i_free_today_at_time: 'Проверить занятость сегодня в указанное время',
  am_i_free_tomorrow_at_time: 'Проверить занятость завтра в указанное время',
  common_free_time_with_contact: 'Общее свободное время с контактом',
  busiest_day_this_week: 'Самый загруженный день недели',
  google_calendar_connection_status: 'Проверить подключение Google Calendar',
  google_calendar_list: 'Список подключённых Google-календарей',
  google_calendar_connect_howto: 'Инструкция подключения Google Calendar',
  google_calendar_disconnect: 'Отключить Google Calendar',
  google_calendar_sync_status: 'Проверить состояние синхронизации',
  google_calendar_reconnect: 'Повторно подключить Google Calendar',
  show_upcoming_holidays: 'Ближайшие праздники',
  show_next_public_holiday: 'Следующий официальный праздник',
  is_today_public_holiday: 'Проверить, праздник ли сегодня',
  show_holidays_this_month: 'Праздники текущего месяца',
  show_holidays_this_year: 'Праздники текущего года',
  bot_capabilities_overview: 'Обзор возможностей бота',
  bot_help_commands: 'Справка по командам',
  bot_hidden_features: 'Дополнительные возможности бота',
  bot_developer_contact: 'Контакт разработчика',
  bot_supported_languages: 'Поддерживаемые языки',
  reminders_for_event: 'Напоминания для указанного события',
  remind_minutes_before_event: 'Напомнить за несколько минут до события',
  remind_hours_before_event: 'Напомнить за несколько часов до события',
  remind_relative_minutes: 'Создать напоминание через несколько минут',
  remind_relative_hours: 'Создать напоминание через несколько часов',
  remind_at_time_today: 'Напомнить сегодня в указанное время',
  remind_recurring_daily: 'Ежедневное напоминание',
  cancel_reminder: 'Отменить напоминание',
  snooze_event_minutes: 'Перенести событие на несколько минут позже',
  snooze_event_hours: 'Перенести событие на несколько часов позже',
  snooze_event_default: 'Отложить обсуждаемое событие',
  move_event_earlier_minutes: 'Перенести событие на несколько минут раньше',
  move_event_earlier_hours: 'Перенести событие на несколько часов раньше',
  move_event_earlier_default: 'Сдвинуть обсуждаемое событие раньше',
  move_event_to_tomorrow: 'Перенести событие на завтра',
  move_event_to_next_week: 'Перенести событие на следующую неделю',
  reschedule_event_to_tomorrow_at_time: 'Перенести на завтра в указанное время',
  view_settings_summary: 'Показать текущие настройки',
  enable_morning_agenda: 'Включить утреннее расписание',
  disable_morning_agenda: 'Выключить утреннее расписание',
  enable_evening_review: 'Включить вечерний обзор',
  disable_evening_review: 'Выключить вечерний обзор',
  set_quiet_hours_night: 'Настроить ночные тихие часы',
  disable_quiet_hours: 'Отключить тихие часы',
  set_default_duration_15: 'Длительность события по умолчанию — 15 минут',
  set_default_duration_30: 'Длительность события по умолчанию — 30 минут',
  enable_voice_responses: 'Включить голосовые ответы',
  disable_voice_responses: 'Выключить голосовые ответы',
  reset_settings_to_default: 'Сбросить настройки к значениям по умолчанию',
  share_agenda_today: 'Поделиться расписанием сегодня',
  share_agenda_tomorrow: 'Поделиться расписанием завтра',
  share_agenda_week: 'Поделиться расписанием недели',
  share_last_event: 'Поделиться последним событием',
  invite_secretary_read: 'Выдать помощнику доступ на чтение',
  invite_secretary_write: 'Выдать помощнику доступ на изменение',
  hide_event_from_sharing: 'Скрыть событие от общего доступа',
  show_event_full_details: 'Показать полные сведения о событии',
  current_time_in_city: 'Текущее время в городе',
  convert_my_time_to_city: 'Перевести своё время в часовой пояс города',
  current_timezone_setting: 'Показать текущий часовой пояс',
  world_clock_common_cities: 'Время в нескольких городах',
  list_common_timezone_shortcuts: 'Справка по часовым поясам',
  time_now_own_timezone: 'Текущее время в своём часовом поясе',
};
